# Generated by Django 5.2 on 2025-06-04 13:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('job', '0010_populate_priority_for_existing_jobs'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PurchaseOrder',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('po_number', models.CharField(max_length=50, unique=True)),
                        ('reference', models.CharField(blank=True, help_text='Optional reference for the purchase order', max_length=100, null=True)),
                        ('order_date', models.DateField(default=django.utils.timezone.now)),
                        ('expected_delivery', models.DateField(blank=True, null=True)),
                        ('xero_id', models.UUIDField(blank=True, null=True, unique=True)),
                        ('xero_tenant_id', models.CharField(blank=True, help_text='For reference only - we are not fully multi-tenant yet', max_length=255, null=True)),
                        ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Supplier'), ('partially_received', 'Partially Received'), ('fully_received', 'Fully Received'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('xero_last_modified', models.DateTimeField(blank=True, null=True)),
                        ('xero_last_synced', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                        ('online_url', models.URLField(blank=True, max_length=500, null=True)),
                        ('job', models.ForeignKey(blank=True, help_text='Primary job this PO is for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.job')),
                        ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='client.client')),
                    ],
                ),
                migrations.CreateModel(
                    name='PurchaseOrderLine',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('description', models.CharField(max_length=200)),
                        ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                        ('price_tbc', models.BooleanField(default=False, help_text='If true, the price is to be confirmed and unit cost will be None')),
                        ('supplier_item_code', models.CharField(blank=True, help_text="Supplier's own item code/SKU", max_length=50, null=True)),
                        ('received_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Total quantity received against this line', max_digits=10)),
                        ('metal_type', models.CharField(blank=True, max_length=100, null=True)),
                        ('alloy', models.CharField(blank=True, help_text='Alloy specification (e.g., 304, 6061)', max_length=50, null=True)),
                        ('specifics', models.CharField(blank=True, help_text='Specific details (e.g., m8 countersunk socket screw)', max_length=255, null=True)),
                        ('location', models.CharField(blank=True, help_text='Where this item will be stored', max_length=255, null=True)),
                        ('dimensions', models.CharField(blank=True, help_text='Dimensions such as length, width, height, etc.', max_length=255, null=True)),
                        ('raw_line_data', models.JSONField(blank=True, help_text='Raw JSON data from the source system or document', null=True)),
                        ('job', models.ForeignKey(blank=True, help_text='The job this purchase line is for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='job.job')),
                        ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_lines', to='purchasing.purchaseorder')),
                    ],
                ),
                migrations.CreateModel(
                    name='PurchaseOrderSupplierQuote',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('filename', models.CharField(max_length=255)),
                        ('file_path', models.CharField(max_length=500)),
                        ('mime_type', models.CharField(blank=True, max_length=100)),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('extracted_data', models.JSONField(blank=True, help_text='Extracted data from the quote', null=True)),
                        ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=20)),
                        ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quote', to='purchasing.purchaseorder')),
                    ],
                ),
            ],
            database_operations=[]  # No database operations - tables already exist
        )
    ]
