# Generated by Django 5.2 on 2025-06-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_move_purchase_models_state"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],  # No state operations - models already defined
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        # Rename tables from workflow to purchasing
                        "RENAME TABLE workflow_purchaseorder TO purchasing_purchaseorder;",
                        "RENAME TABLE workflow_purchaseorderline TO purchasing_purchaseorderline;", 
                        "RENAME TABLE workflow_purchaseordersupplierquote TO purchasing_purchaseordersupplierquote;",
                    ],
                    reverse_sql=[
                        # Reverse operation - rename back to workflow
                        "RENAME TABLE purchasing_purchaseorder TO workflow_purchaseorder;",
                        "RENAME TABLE purchasing_purchaseorderline TO workflow_purchaseorderline;",
                        "RENAME TABLE purchasing_purchaseordersupplierquote TO workflow_purchaseordersupplierquote;",
                    ]
                )
            ]
        )
    ]
