# Generated by Django 5.2 on 2025-06-04 13:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


# !!!!!!!
# WARNING: This migration is designed to move purchase models from the workflow app to the purchasing app. It should be faked in existing databases.
class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_move_purchase_models_state"),
        ("workflow", "0067_supplier_purchase_purchaseline_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],  # No state operations - models already defined
            database_operations=[
                # No database operations - tables already exist from workflow migration
            ],
        )
    ]

