# Generated by Django 5.2 on 2025-06-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0002_move_purchase_models_database"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminum", "Aluminum"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                default="unspecified",
                max_length=100,
                null=True,
            ),
        ),
    ]
