# Generated by Django 5.2 on 2025-06-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0012_merge_20250604_2123"),
        ("purchasing", "0005_add_stock_in_database"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="item_code",
            field=models.CharField(
                blank=True,
                help_text="Xero Item Code",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="xero_id",
            field=models.CharField(
                blank=True,
                help_text="Unique ID from Xero for this item",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="xero_last_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Last modified date from Xero for this item",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="raw_json",
            field=models.JSONField(
                blank=True,
                help_text="Raw JSON data from Xero for this item",
                null=True,
            ),
        ),
    ]
