# Generated by Django 5.2 on 2025-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0006_add_stock_item_code_xero_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("xero_id",), name="unique_xero_id_stock"
            ),
        ),
    ]
