# Generated by Django 5.2 on 2025-05-10 21:16

import uuid

import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalStaff",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("icon", models.TextField(blank=True, max_length=100, null=True)),
                ("password_needs_reset", models.BooleanField(default=False)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "wage_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ims_payroll_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("raw_ims_data", models.JSONField(blank=True, default=dict, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "hours_mon",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Monday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_tue",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Tuesday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_wed",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Wednesday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_thu",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Thursday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_fri",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Friday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_sat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard hours for Saturday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_sun",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard hours for Sunday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Staff Member",
                "verbose_name_plural": "historical Staff Members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
                "db_table": "workflow_historicalstaff",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="staff_icons/"),
                ),
                ("password_needs_reset", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "wage_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "ims_payroll_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("raw_ims_data", models.JSONField(blank=True, default=dict, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "hours_mon",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Monday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_tue",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Tuesday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_wed",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Wednesday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_thu",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Thursday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_fri",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Standard hours for Friday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_sat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard hours for Saturday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
                (
                    "hours_sun",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Standard hours for Sunday, 0 for non-working day",
                        max_digits=4,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "db_table": "workflow_staff",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
