# Generated by Django 5.2 on 2025-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaff",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="staff",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
