# This file is autogenerated by update_init.py script

from .client_view import ClientListView, ClientUpdateView, UnusedClientsView
from .dashboard_view import DashboardView
from .delivery_receipt_view import DeliveryReceiptListView, DeliveryReceiptCreateView
from .job_file_upload import JobFileUploadView
from .job_file_view import BinaryFileRenderer, JobFileView
from .password_views import SecurityPasswordChangeView
from .purchase_order_view import PurchaseOrderListView, PurchaseOrderCreateView
from .report_view import ReportsIndexView, CompanyProfitAndLossView
from .staff_view import StaffListAPIView, StaffListView, StaffCreateView, StaffUpdateView
from .time_entry_view import TimesheetEntryView
from .workshop_view import WorkshopPDFView

__all__ = [
    'ClientListView',
    'ClientUpdateView',
    'UnusedClientsView',
    'DashboardView',
    'DeliveryReceiptListView',
    'DeliveryReceiptCreateView',
    'JobFileUploadView',
    'BinaryFileRenderer',
    'JobFileView',
    'SecurityPasswordChangeView',
    'PurchaseOrderListView',
    'PurchaseOrderCreateView',
    'ReportsIndexView',
    'CompanyProfitAndLossView',
    'StaffListAPIView',
    'StaffListView',
    'StaffCreateView',
    'StaffUpdateView',
    'TimesheetEntryView',
    'WorkshopPDFView',
]
