# Generated by Django 5.2 on 2025-06-02 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0001_initial"),
        ("workflow", "0151_remove_purchaseline_purchase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original filename of the uploaded price list",
                        max_length=255,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="workflow.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Price List",
                "verbose_name_plural": "Supplier Price Lists",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="supplierproduct",
            name="price_list",
            field=models.ForeignKey(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="quoting.supplierpricelist",
            ),
            preserve_default=False,
        ),
    ]
