# This file is autogenerated by update_init.py script

from .kpi_view import KPICalendarTemplateView, KPICalendarAPIView

from .submit_quote_view import generate_quote_pdf, send_quote_email

__all__ = [
    'KPICalendarTemplateView',
    'KPICalendarAPIView',
    'generate_quote_pdf',
    'send_quote_email',
]
