# Generated by Django 5.2 on 2025-05-13 14:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("job", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.CreateModel(
                    name="TimeEntry",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "date",
                            models.DateField(
                                blank=True,
                                help_text="The date of the time entry.  Ie. the date the work was done.",
                                null=True,
                            ),
                        ),
                        ("note", models.TextField(blank=True, null=True)),
                        (
                            "is_billable",
                            models.BooleanField(
                                default=True,
                                help_text="Set to false to avoid billing the client.  E.g. fixup work",
                            ),
                        ),
                        (
                            "wage_rate",
                            models.DecimalField(decimal_places=2, max_digits=10),
                        ),
                        (
                            "charge_out_rate",
                            models.DecimalField(decimal_places=2, max_digits=10),
                        ),
                        (
                            "wage_rate_multiplier",
                            models.DecimalField(
                                decimal_places=2,
                                default=1,
                                help_text="Multiplier for hourly rate. Example: 2.0 for double time. 0 means no paid. 1 means normal rate.",
                                max_digits=5,
                            ),
                        ),
                        ("description", models.TextField(default="")),
                        (
                            "hours",
                            models.DecimalField(
                                decimal_places=2, default=0, max_digits=10
                            ),
                        ),
                        ("items", models.IntegerField(blank=True, null=True)),
                        (
                            "minutes_per_item",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=8, null=True
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "job_pricing",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="time_entries",
                                to="job.jobpricing",
                            ),
                        ),
                        (
                            "staff",
                            models.ForeignKey(
                                blank=True,
                                help_text="The Staff member who did the work.  Null for estimates/quotes.",
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="time_entries",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "workflow_timeentry",
                        "ordering": ["created_at"],
                    },
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="TimeEntry",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "date",
                            models.DateField(
                                blank=True,
                                help_text="The date of the time entry.  Ie. the date the work was done.",
                                null=True,
                            ),
                        ),
                        ("note", models.TextField(blank=True, null=True)),
                        (
                            "is_billable",
                            models.BooleanField(
                                default=True,
                                help_text="Set to false to avoid billing the client.  E.g. fixup work",
                            ),
                        ),
                        (
                            "wage_rate",
                            models.DecimalField(decimal_places=2, max_digits=10),
                        ),
                        (
                            "charge_out_rate",
                            models.DecimalField(decimal_places=2, max_digits=10),
                        ),
                        (
                            "wage_rate_multiplier",
                            models.DecimalField(
                                decimal_places=2,
                                default=1,
                                help_text="Multiplier for hourly rate. Example: 2.0 for double time. 0 means no paid. 1 means normal rate.",
                                max_digits=5,
                            ),
                        ),
                        ("description", models.TextField(default="")),
                        (
                            "hours",
                            models.DecimalField(
                                decimal_places=2, default=0, max_digits=10
                            ),
                        ),
                        ("items", models.IntegerField(blank=True, null=True)),
                        (
                            "minutes_per_item",
                            models.DecimalField(
                                blank=True, decimal_places=2, max_digits=8, null=True
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "job_pricing",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="time_entries",
                                to="job.jobpricing",
                            ),
                        ),
                        (
                            "staff",
                            models.ForeignKey(
                                blank=True,
                                help_text="The Staff member who did the work.  Null for estimates/quotes.",
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="time_entries",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "workflow_timeentry",
                        "ordering": ["created_at"],
                    },
                ),
            ],
        )
    ]
