# Generated by Django 5.2 on 2025-06-03 13:43

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    state_operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xero_contact_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_account_customer", models.BooleanField(default=False)),
                ("xero_last_modified", models.DateTimeField()),
                ("raw_json", models.JSONField(blank=True, null=True)),
                (
                    "primary_contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "primary_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "additional_contact_persons",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("all_phones", models.JSONField(blank=True, default=list, null=True)),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
            options={
                "db_table": "workflow_client",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("client.client",),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
