# Generated by Django 5.2 on 2025-06-09 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the contact person", max_length=255
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the contact",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone number of the contact",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Job title if it's helpful - else leave blank",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this is the primary contact for the client",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this contact",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this contact belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Contact",
                "verbose_name_plural": "Client Contacts",
                "db_table": "client_contact",
                "ordering": ["-is_primary", "name"],
            },
        ),
    ]
