# Generated by Django 5.2 on 2025-06-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_clientcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                help_text="The client this was merged into",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_from_clients",
                to="client.client",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="xero_archived",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this client has been archived/merged in Xero",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="xero_merged_into_id",
            field=models.CharField(
                blank=True,
                help_text="The Xero contact ID this client was merged into (temporary storage)",
                max_length=255,
                null=True,
            ),
        ),
    ]
