# Generated by Django 5.2 on 2025-05-22 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_historicaljob_pricing_type_and_more"),
        ("timesheet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="job_pricing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="job.jobpricing",
            ),
        ),
    ]
