# Generated by Django 5.2 on 2025-05-28 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_part_adjustmententry_part_materialentry_part"),
        ("timesheet", "0002_alter_timeentry_job_pricing_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="part",
            field=models.ForeignKey(
                blank=True,
                help_text="The part this time entry belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="job.part",
            ),
        ),
    ]
