# Generated by Django 5.2 on 2025-05-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0003_timeentry_part"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeentry",
            name="job_pricing",
        ),
    ]