# Generated by Django 5.2 on 2025-05-31 10:27

import django.db.models.deletion
from django.db import migrations, models


def validate_timeentry_parts_exist(apps, schema_editor):
    """Validate that all TimeEntry records have parts assigned"""
    TimeEntry = apps.get_model("timesheet", "TimeEntry")
    
    # Check TimeEntry records
    time_entries_without_parts = TimeEntry.objects.filter(part__isnull=True).count()
    if time_entries_without_parts > 0:
        raise Exception(
            f"Cannot proceed: {time_entries_without_parts} TimeEntry records "
            "do not have parts assigned. Please run the data migration first."
        )
    
    print(f"✓ Validation passed: All TimeEntry records have parts assigned")


def reverse_validation(apps, schema_editor):
    """No validation needed for reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0011_remove_entry_job_pricing_fields"),
        ("timesheet", "0004_remove_timeentry_job_pricing"),
    ]

    operations = [
        migrations.RunPython(validate_timeentry_parts_exist, reverse_validation),
        migrations.AlterField(
            model_name="timeentry",
            name="part",
            field=models.ForeignKey(
                help_text="The part this time entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="job.part",
            ),
        ),
    ]