# This file is autogenerated by update_init.py script

from .client_rest_views import (
    BaseClientRestView,
    ClientContactCreateRestView,
    ClientContactsRestView,
    ClientCreateRestView,
    ClientListAllRestView,
    ClientSearchRestView,
)
from .client_views import ClientListView, ClientUpdateView

__all__ = [
    "BaseClientRestView",
    "ClientListAllRestView",
    "ClientSearchRestView",
    "ClientContactsRestView",
    "ClientContactCreateRestView",
    "ClientCreateRestView",
    "ClientListView",
    "ClientUpdateView",
]
