# Generated by Django 5.0.6 on 2024-09-19 02:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_contact_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_account_customer", models.BooleanField(default=False)),
                ("raw_json", models.JSONField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_client",
            },
        ),
        migrations.CreateModel(
            name="XeroAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "account_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "account_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                ("enable_payments", models.BooleanField(default=False)),
                ("last_modified", models.DateTimeField()),
                ("raw_json", models.JSONField()),
            ],
            options={
                "db_table": "workflow_xeroaccount",
            },
        ),
        migrations.CreateModel(
            name="XeroToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(max_length=100, unique=True)),
                ("token_type", models.CharField(max_length=50)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "workflow_xerotoken",
            },
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("number", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AUTHORISED", "Authorised"),
                            ("DELETED", "Deleted"),
                            ("VOIDED", "Voided"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_modified", models.DateTimeField()),
                ("raw_json", models.JSONField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill",
                "verbose_name_plural": "Bills",
                "db_table": "workflow_bill",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("number", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AUTHORISED", "Authorised"),
                            ("DELETED", "Deleted"),
                            ("VOIDED", "Voided"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_modified", models.DateTimeField()),
                ("raw_json", models.JSONField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "workflow_invoice",
            },
        ),
    ]
