# Generated by Django 5.0.6 on 2024-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0004_companydefaults_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companydefaults",
            name="id",
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="company_name",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
