# Generated by Django 5.0.6 on 2024-09-26 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0005_remove_companydefaults_id_and_more"),
        ("job", "0001_initial"),
    ]

    operations = []
