# Generated by Django 5.0.6 on 2024-09-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_quotepricing"),
    ]

    operations = [
    ]
