# Generated by Django 5.0.6 on 2024-09-30 00:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0008_remove_jobpricing_job_pricing_number"),
    ]

    operations = []
