# Generated by Django 5.0.6 on 2024-10-01 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0011_remove_timeentry_minutes_timeentry_description_and_more"),
    ]

    operations = []
