# Generated by Django 5.0.6 on 2024-10-01 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_alter_timeentry_staff"),
    ]

    operations = [
    ]
