# Generated by Django 5.0.6 on 2024-10-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0013_alter_timeentry_date"),
    ]

    operations = [

    ]
