# Generated by Django 5.0.6 on 2024-10-01 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0015_historicaljob_delivery_date_job_delivery_date"),
    ]

    operations = []
