# Generated by Django 5.0.6 on 2024-10-02 01:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0017_materialentry_comments"),
    ]

    operations = []
