# Generated by Django 5.0.6 on 2024-11-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0019_alter_historicaljob_delivery_date_and_more"),
    ]

    operations = [
    ]
