# Generated by Django 5.0.6 on 2024-11-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0020_historicaljob_material_gauge_quantity_and_more"),
    ]

    operations = [
    ]
