# Generated by Django 5.0.6 on 2024-11-06 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0024_alter_jobpricing_options_jobpricing_revision_number"),
    ]

    operations = [

    ]
