# Generated by Django 5.0.6 on 2024-11-06 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0024_alter_jobpricing_options_jobpricing_revision_number"),
    ]

    operations = []
