# Generated by Django 5.0.6 on 2024-11-16 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0027_remove_jobpricing_job"),
    ]

    operations = []
