# Generated by Django 5.0.6 on 2024-11-16 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0028_jobpricing_job"),
    ]

    operations = [
    ]
