# Generated by Django 5.0.6 on 2024-11-16 04:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0030_alter_jobpricing_job"),
    ]

    operations = []
