# Generated by Django 5.0.6 on 2024-11-16 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0031_alter_jobpricing_job"),
    ]

    operations = [
    ]
