# Generated by Django 5.0.6 on 2024-11-16 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0034_alter_materialentry_quantity_and_more"),
    ]

    operations = [
    ]
