# Generated by Django 5.0.6 on 2024-11-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0034_alter_materialentry_quantity_and_more"),
    ]

    operations = [
    ]
