# Generated by Django 5.0.6 on 2024-11-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow",
            "0036_historicalstaff_hours_fri_historicalstaff_hours_mon_and_more",
        ),
    ]

    operations = []