# Generated by Django 5.0.6 on 2024-11-18 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0037_remove_historicalstaff_charge_out_rate_and_more"),
    ]

    operations = []
