# Generated by Django 5.0.6 on 2024-11-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0040_alter_historicaljob_charge_out_rate_and_more"),
    ]

    operations = []