# Generated by Django 5.0.6 on 2024-11-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0041_timeentry_wage_rate_multiplier"),
    ]

    operations = []