# Generated by Django 5.0.6 on 2024-11-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0042_jobpricing_job"),
    ]

    operations = []
