# Generated by Django 5.0.6 on 2024-11-21 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0043_alter_jobpricing_job"),
    ]

    operations = []
