# Generated by Django 5.0.6 on 2024-11-21 23:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0046_alter_adjustmententry_options_alter_bill_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="last_modified",
            new_name="xero_last_modified",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="last_modified",
            new_name="xero_last_modified",
        ),
        migrations.RenameField(
            model_name="xeroaccount",
            old_name="last_modified",
            new_name="xero_last_modified",
        ),
        migrations.AddField(
            model_name="client",
            name="xero_last_modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
