# Generated by Django 5.0.6 on 2024-11-22 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0048_billlineitem_xero_id_invoicelineitem_xero_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
