# Generated by Django 5.0.6 on 2024-11-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0049_companydefaults_created_at_and_more"),
    ]

    operations = []
