# Generated by Django 5.0.6 on 2024-11-22 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0050_alter_historicalstaff_created_at_and_more"),
    ]

    operations = []
