# Generated by Django 5.0.6 on 2024-11-22 20:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0051_alter_historicalstaff_updated_at_and_more"),
    ]

    operations = []
