# Generated by Django 5.0.6 on 2024-11-22 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0052_alter_jobpricing_job"),
    ]

    operations = []
