# Generated by Django 5.0.6 on 2024-11-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0053_alter_job_latest_estimate_pricing_and_more"),
    ]

    operations = [
    ]
