# Generated by Django 5.0.6 on 2024-11-22 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0054_remove_historicaljob_shop_job_remove_job_shop_job_and_more"),
    ]

    operations = [
    ]
