# Generated by Django 5.0.6 on 2024-11-23 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0055_alter_historicaljob_description_and_more"),
    ]

    operations = []
