# Generated by Django 5.0.6 on 2024-11-23 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0056_rename_total_bill_total_excl_tax_and_more"),
    ]

    operations = [
    ]
