# Generated by Django 5.0.6 on 2024-12-06 07:37


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "workflow",
            "0057_rename_line_amount_billlineitem_line_amount_excl_tax_and_more",
        ),
    ]

    operations = []
