# Generated by Django 5.0.6 on 2024-12-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0063_rename_date_xerojournal_journal_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xerojournallineitem",
            name="xero_last_modified",
        ),
    ]
