# Generated by Django 5.0.6 on 2024-12-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0064_remove_xerojournallineitem_xero_last_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xerojournal",
            name="journal_number",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
