# Generated by Django 5.1.4 on 2025-01-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0065_alter_xerojournal_journal_number"),
    ]

    operations = [
    ]