# Generated by Django 5.1.4 on 2025-01-10 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0067_jobfile_status"),
    ]

    operations = []
