# Generated by Django 5.1.4 on 2025-01-13 19:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0068_purchase_created_at_purchase_updated_at_and_more"),
        ("workflow", "0071_alter_jobevent_timestamp"),
    ]

    operations = []
