# Generated by Django 5.1.4 on 2025-01-21 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0072_merge_20250113_1626"),
    ]

    operations = []
