# Generated by Django 5.1.4 on 2025-01-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0073_jobpricing_is_historical"),
    ]

    operations = [
    ]
