# Generated by Django 5.1.5 on 2025-02-06 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0074_bill_xero_last_synced_client_xero_last_synced_and_more"),
    ]

    operations = []
