# Generated by Django 5.1.4 on 2025-02-03 20:56


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0074_bill_xero_last_synced_client_xero_last_synced_and_more"),
    ]

    operations = []
