# Generated by Django 5.1.4 on 2025-02-03 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0075_invoice_online_url_quote"),
    ]

    operations = []
