# Generated by Django 5.1.5 on 2025-02-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0079_merge_20250207_1950"),
    ]

    operations = [
    ]