# Generated by Django 5.1.5 on 2025-03-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0079_merge_20250207_1950"),
    ]

    operations = []
