# Generated by Django 5.1.5 on 2025-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0084_cleanup_company_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="xerotoken",
            name="scope",
            field=models.TextField(default="PLACEHOLDER_SCOPE_WILL_BE_REPLACED"),
        ),
    ]
