# Generated by Django 5.1.5 on 2025-03-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0085_auto_20250302_2205"),
    ]

    operations = []
