# Generated by Django 5.1.5 on 2025-03-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0088_merge_20250305_0549'),
    ]

    operations = [
    ]
