# Generated by Django 5.1.5 on 2025-03-09 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0091_rename_coolected_historicaljob_collected_and_more"),
    ]

    operations = []
