# Generated by Django 5.1.5 on 2025-03-09 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0093_historicaljob_notes_job_notes"),
    ]

    operations = []
