# Generated by Django 5.1.5 on 2025-03-10 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0094_migrate_material_gauge_to_notes"),
    ]

    operations = []
