# Generated by Django 5.1.5 on 2025-03-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0090_alter_staff_options"),
        ("workflow", "0095_alter_staff_options_and_more"),
    ]

    operations = []
