# Generated by Django 5.1.5 on 2025-03-13 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0096_merge_20250310_2039"),
    ]

    operations = []
