# Generated by Django 5.1.5 on 2025-03-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0097_alter_historicalstaff_ims_payroll_id_and_more"),
    ]

    operations = []
