# Generated by Django 5.1.5 on 2025-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0102_add_job_to_purchase_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="starting_po_number",
            field=models.IntegerField(
                default=1,
                help_text="Helper field to set the starting purchase order number",
            ),
        ),
    ]
