# Generated by Django 5.1.5 on 2025-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0106_add_price_tbc_to_purchase_order_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="online_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="raw_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
