# Generated by Django 5.1.5 on 2025-03-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0109_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="Optional reference for the purchase order",
                max_length=100,
                null=True,
            ),
        ),
    ]
