# Generated by Django 5.1.5 on 2025-03-31 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0111_alter_timeentry_minutes_per_item"),
    ]

    operations = []
