# Generated by Django 5.1.5 on 2025-03-31 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0112_remove_purchaseline_purchase_and_more"),
    ]

    operations = []
