# Generated by Django 5.1.5 on 2025-03-31 20:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0113_remove_stock_source_id_materialentry_source_stock_and_more"),
    ]

    operations = []
