# Generated by Django 5.1.5 on 2025-03-31 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0115_alter_stock_id"),
    ]

    operations = []
