# Generated by Django 5.1.5 on 2025-03-31 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0116_stock_alloy_stock_location_stock_metal_type_and_more"),
    ]

    operations = []
