# Generated by Django 5.1.5 on 2025-03-31 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0117_alter_stock_metal_type"),
    ]

    operations = []
