# Generated by Django 5.1.5 on 2025-04-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0119_alter_materialentry_source_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted to Supplier"),
                    ("partially_received", "Partially Received"),
                    ("fully_received", "Fully Received"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
