# Generated by Django 5.1.5 on 2025-04-17 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0122_companydefaults_anthropic_api_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="workflow.client",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseordersupplierquote",
            name="purchase_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_quote",
                to="workflow.purchaseorder",
            ),
        ),
    ]
