# Generated by Django 5.1.5 on 2025-04-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0127_remove_purchaseorder_raw_json_and_more"),
    ]

    operations = [
    ]
