# Generated by Django 5.2 on 2025-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0129_companydefaults_gemini_api_key_stock_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="raw_line_data",
            field=models.JSONField(
                blank=True,
                help_text="Raw JSON data from the source system or document",
                null=True,
            ),
        )
    ]
