# Generated by Django 5.2 on 2025-05-01 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0130_purchaseorderline_raw_line_data_stock_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydefaults",
            name="anthropic_api_key",
            field=models.CharField(
                blank=True,
                help_text="(DEPRECATED) API key for Anthropic Claude LLM",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="gemini_api_key",
            field=models.CharField(
                blank=True,
                help_text="(DEPRECATED) API key for Google Gemini LLM",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this provider", max_length=100
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key for this AI Provider",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[("Claude", "Anthropic"), ("Gemini", "Google")],
                        help_text="Type of AI provider",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_providers",
                        to="workflow.companydefaults",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Provider",
                "verbose_name_plural": "AI Providers",
            },
        ),
    ]
