# Generated by Django 5.1.5 on 2025-05-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0136_rename_job_status"),
    ]

    operations = [
    ]
