# Generated by Django 5.1.5 on 2025-05-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0137_auto_20250508_2012"),
    ]

    operations = [
    ]
