# Generated by Django 5.1.5 on 2025-05-08 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0140_remove_staff_groups_remove_staff_user_permissions_and_more"),
    ]

    operations = []
