# Generated by Django 5.1.5 on 2025-05-08 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0142_remove_historicaljob_client_and_more"),
    ]

    operations = []
