# Generated by Django 5.2 on 2025-05-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0148_client_primary_contact_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="secondary_contact_email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="secondary_contact_name",
        ),
        migrations.AddField(
            model_name="client",
            name="additional_contact_persons",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
