# Generated by Django 5.2 on 2025-05-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0149_remove_client_secondary_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="all_phones",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
