# Generated by Django 5.2 on 2025-06-02 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0151_remove_purchaseline_purchase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companydefaults",
            name="anthropic_api_key",
        ),
        migrations.RemoveField(
            model_name="companydefaults",
            name="gemini_api_key",
        ),
    ]
