# Generated by Django 5.2 on 2025-06-03 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
        ("job", "0010_populate_priority_for_existing_jobs"),
        ("quoting", "0002_supplierpricelist_supplierproduct_price_list"),
        ("workflow", "0152_remove_companydefaults_anthropic_api_key_and_more"),
    ]

    state_operations = [
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.CreateModel(
            name="Client",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("client.client",),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        )
    ]
