# Generated by Django 5.2 on 2025-06-04 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0153_delete_client_client"),
        ("purchasing", "0002_move_purchase_models_database"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="PurchaseOrder"),
                migrations.DeleteModel(name="PurchaseOrderLine"), 
                migrations.DeleteModel(name="PurchaseOrderSupplierQuote"),
            ],
            database_operations=[
                # No database operations - tables were already renamed by purchasing app
            ],
        ),
    ]
