# Generated by Django 5.2 on 2025-06-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_alter_purchaseorder_xero_tenant_id_and_more"),
        ("workflow", "0154_auto_20250604_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchasing.purchaseorder",),
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchasing.purchaseorderline",),
        ),
        migrations.CreateModel(
            name="PurchaseOrderSupplierQuote",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchasing.purchaseordersupplierquote",),
        ),
    ]
