# Generated by Django 5.2 on 2025-06-04 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_alter_purchaseorder_xero_tenant_id_and_more"),
        ("workflow", "0154_auto_20250604_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchasing.purchaseorder",),
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchasing.purchaseorderline",),
        ),
        migrations.CreateModel(
            name="PurchaseOrderSupplierQuote",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchasing.purchaseordersupplierquote",),
        ),
        migrations.AlterField(
            model_name="stock",
            name="source_purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The PO line this stock originated from (if source='purchase_order')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_generated",
                to="workflow.purchaseorderline",
            ),
        ),
    ]
