# Generated by Django 5.2 on 2025-06-05 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0013_merge_20250605_0811"),
        ("purchasing", "0007_stock_unique_xero_id"),
        ("workflow", "0155_remove_stock_job_remove_stock_source_parent_stock_and_more"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="stock",
            name="job",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="source_parent_stock",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="source_purchase_order_line",
        ),
        migrations.DeleteModel(
            name="PurchaseOrder",
        ),
        migrations.DeleteModel(
            name="PurchaseOrderLine",
        ),
        migrations.DeleteModel(
            name="PurchaseOrderSupplierQuote",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("purchasing.stock",),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
