# Generated by Django 5.2 on 2025-06-04 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0003_alter_purchaseorder_xero_tenant_id_and_more"),
        ("workflow", "0155_purchaseorder_purchaseorderline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="source_purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The PO line this stock originated from (if source='purchase_order')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_generated",
                to="purchasing.purchaseorderline",
            ),
        ),
    ]
