# Generated by Django 5.2 on 2025-06-05 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
        ("workflow", "0156_remove_stock_job_remove_stock_source_parent_stock_and_more"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="bill",
            name="client",
        ),
        migrations.RemoveField(
            model_name="billlineitem",
            name="bill",
        ),
        migrations.RemoveField(
            model_name="billlineitem",
            name="account",
        ),
        migrations.RemoveField(
            model_name="creditnote",
            name="client",
        ),
        migrations.RemoveField(
            model_name="creditnotelineitem",
            name="credit_note",
        ),
        migrations.RemoveField(
            model_name="creditnotelineitem",
            name="account",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="client",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="job",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="invoice",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="account",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="client",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="job",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.DeleteModel(
            name="BillLineItem",
        ),
        migrations.DeleteModel(
            name="CreditNote",
        ),
        migrations.DeleteModel(
            name="CreditNoteLineItem",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceLineItem",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounting.bill",),
        ),
        migrations.CreateModel(
            name="BillLineItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounting.billlineitem",),
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounting.creditnote",),
        ),
        migrations.CreateModel(
            name="CreditNoteLineItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounting.creditnotelineitem",),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounting.invoice",),
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounting.invoicelineitem",),
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounting.quote",),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations, database_operations=[]
        )
    ]
