# Generated by Django 5.2 on 2025-06-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0157_remove_bill_client_remove_billlineitem_bill_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bill",
        ),
        migrations.DeleteModel(
            name="BillLineItem",
        ),
        migrations.DeleteModel(
            name="CreditNote",
        ),
        migrations.DeleteModel(
            name="CreditNoteLineItem",
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="InvoiceLineItem",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
    ]
