# Generated by Django 5.2 on 2025-06-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0158_delete_bill_delete_billlineitem_delete_creditnote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="shop_client_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the internal shop client for tracking shop work (e.g., 'MSM (Shop)')",
                max_length=255,
                null=True,
            ),
        ),
    ]
