# Generated by Django 5.2 on 2025-06-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0159_add_shop_client_name_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprovider",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("Claude", "Anthropic"),
                    ("Gemini", "Google"),
                    ("Mistral", "Mistral"),
                ],
                help_text="Type of AI provider",
                max_length=20,
            ),
        ),
    ]
