# Generated by Django 5.2 on 2025-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0160_alter_aiprovider_provider_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="gdrive_quotes_folder_id",
            field=models.UUIDField(
                blank=True,
                help_text="Google Drive folder ID for storing quotes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="gdrive_quotes_folder_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the Google Drive folder for storing quotes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="master_quote_template_id",
            field=models.UUIDField(
                blank=True,
                help_text="Google Sheets ID for the quote template",
                null=True,
            ),
        ),
    ]
