# Generated by Django 5.2 on 2025-06-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0161_companydefaults_gdrive_quotes_folder_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydefaults",
            name="gdrive_quotes_folder_id",
            field=models.CharField(
                blank=True,
                help_text="Google Drive folder ID for storing quotes",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="master_quote_template_id",
            field=models.CharField(
                blank=True,
                help_text="Google Sheets ID for the quote template",
                max_length=100,
                null=True,
            ),
        ),
    ]
