# Generated by Django 5.2 on 2025-06-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0162_alter_companydefaults_gdrive_quotes_folder_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiprovider",
            name="active",
        ),
        migrations.AddField(
            model_name="aiprovider",
            name="default",
            field=models.BooleanField(
                default=False, help_text="Use this provider as the default"
            ),
        ),
        migrations.AddField(
            model_name="aiprovider",
            name="model_name",
            field=models.CharField(
                blank=True,
                help_text="Specific model name (e.g., gemini-2.5-flash-lite-preview-06-17)",
                max_length=100,
            ),
        ),
    ]
