# Generated by Django 5.2 on 2025-06-21 05:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0163_rename_active_to_default_add_model_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name (e.g., 'Chatbot Service')",
                        max_length=100,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="API key for authentication",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service API Key",
                "verbose_name_plural": "Service API Keys",
                "db_table": "workflow_service_api_key",
            },
        ),
    ]
