# Generated by Django 5.2 on 2025-06-28 20:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0165_app_error_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apperror",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Application Error",
                "verbose_name_plural": "Application Errors",
            },
        ),
        migrations.AlterModelOptions(
            name="xeroerror",
            options={
                "verbose_name": "Xero Error",
                "verbose_name_plural": "Xero Errors",
            },
        ),
        migrations.AlterField(
            model_name="apperror",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
