# Generated by Django 5.2 on 2025-05-21 00:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
        ("workflow", "0143_alter_stock_job"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="historicaljob",
                    name="pricing_methodology",
                    field=models.CharField(
                        choices=[
                            ("time_materials", "Time and Materials"),
                            ("fixed_price", "Fixed Price"),
                        ],
                        default="time_materials",
                        help_text="Type of pricing for the job (fixed price or time and materials).",
                        max_length=20,
                    ),
                ),
                migrations.AlterField(
                    model_name="job",
                    name="pricing_methodology",
                    field=models.CharField(
                        choices=[
                            ("time_materials", "Time and Materials"),
                            ("fixed_price", "Fixed Price"),
                        ],
                        default="time_materials",
                        help_text="Type of pricing for the job (fixed price or time and materials).",
                        max_length=20,
                    ),
                ),
                migrations.CreateModel(
                    name="AdjustmentEntry",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "description",
                            models.CharField(blank=True, default="", max_length=200),
                        ),
                        (
                            "cost_adjustment",
                            models.DecimalField(
                                decimal_places=2, default=0.0, max_digits=10
                            ),
                        ),
                        (
                            "price_adjustment",
                            models.DecimalField(
                                decimal_places=2, default=0.0, max_digits=10
                            ),
                        ),
                        (
                            "comments",
                            models.CharField(blank=True, default="", max_length=200),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "job_pricing",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="adjustment_entries",
                                to="job.jobpricing",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "workflow_adjustmententry",
                        "ordering": ["created_at"],
                    },
                ),
                migrations.CreateModel(
                    name="MaterialEntry",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "item_code",
                            models.CharField(blank=True, default="", max_length=20),
                        ),
                        (
                            "description",
                            models.CharField(blank=True, default="", max_length=200),
                        ),
                        (
                            "comments",
                            models.CharField(blank=True, default="", max_length=200),
                        ),
                        (
                            "quantity",
                            models.DecimalField(
                                decimal_places=2, default=0, max_digits=10
                            ),
                        ),
                        (
                            "unit_cost",
                            models.DecimalField(
                                decimal_places=2, default=0, max_digits=10
                            ),
                        ),
                        (
                            "unit_revenue",
                            models.DecimalField(
                                decimal_places=2, default=0, max_digits=10
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        (
                            "job_pricing",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="material_entries",
                                to="job.jobpricing",
                            ),
                        ),
                        (
                            "purchase_order_line",
                            models.ForeignKey(
                                blank=True,
                                help_text="Convenience link to original PO line (derived via source_stock)",
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="material_entries",
                                to="purchasing.purchaseorderline",
                            ),
                        ),
                        (
                            "source_stock",
                            models.ForeignKey(
                                blank=True,
                                help_text="The Stock item consumed to create this entry",
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="consumed_entries",
                                to="workflow.stock",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "workflow_materialentry",
                        "ordering": ["created_at"],
                    },
                ),
            ],
        ),
    ]
