# Generated by Django 5.2 on 2025-05-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_alter_historicaljob_pricing_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
