# Generated by Django 5.2 on 2025-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_historicaljob_contact_email_job_contact_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
