# Generated by Django 5.2 on 2025-06-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_add_materialentry_add_adjustmententry"),
    ]

    operations = [
        # No operations needed - JobPart table is now created correctly from the start
    ]
