# Generated by Django 5.2 on 2025-06-04 11:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


# This migration is meant to be faked in existing dbs. Its only purpose is to create the tables when creating a fresh db.
class Migration(migrations.Migration):
    dependencies = [
        ("job", "0006_add_material_adjustment_jobpart_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item_code", models.CharField(blank=True, default="", max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("comments", models.CharField(blank=True, default="", max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unit_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_entries",
                        to="job.jobpricing",
                    ),
                ),
                (
                    "source_stock",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Stock item consumed to create this entry",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumed_entries",
                        to="workflow.stock",
                    ),
                ),
                # purchase_order_line will be created in a fresh db after purchasing app is effectively migrated
            ],
            options={
                "db_table": "workflow_materialentry",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdjustmentEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "cost_adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "revenue_adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_entries",
                        to="job.jobpricing",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_adjustmententry",
                "ordering": ["created_at"],
            },
        ),
    ]
