# Generated by Django 5.2 on 2025-06-03 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0008_alter_jobpart_options_and_more"),
        ("workflow", "0152_remove_companydefaults_anthropic_api_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Priority of the job, lower numbers are higher priority.",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Priority of the job, lower numbers are higher priority.",
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "priority"], name="job_priority_status_idx"
            ),
        ),
    ]
