# Generated by Django 5.2 on 2025-06-03 10:55

from django.db import migrations


def populate_priority_for_existing_jobs(apps, schema_editor):
    Job = apps.get_model("job", "Job")

    PRIORITY_INCREMENT = 200
    statuses = Job.objects.values_list("status", flat=True).distinct()

    for status in statuses:
        jobs = Job.objects.filter(status=status).order_by("-job_number")
        for i, job in enumerate(jobs, start=1):
            job.priority = i * PRIORITY_INCREMENT
            job.save(update_fields=["priority"])


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0009_historicaljob_priority_job_priority_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_priority_for_existing_jobs, migrations.RunPython.noop
        ),
    ]
