# Generated by Django 5.2 on 2025-06-04 16:20

import django.db.models.deletion
from django.db import migrations, models


# !!!!!!!
# WARNING - Before applying this migration, check migration 0007_add_materialentry_add_adjustmententry.
# The existing vs. fresh db situation is the same here.
class Migration(migrations.Migration):
    dependencies = [
        ("job", "0010_populate_priority_for_existing_jobs"),
        ("purchasing", "0002_move_purchase_models_database"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialentry",
            name="purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Convenience link to original PO line (derived via source_stock)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_entries",
                to="purchasing.PurchaseOrderLine",  # Now referencing the new app
            ),
        ),
    ]
