# Generated by Django 5.2 on 2025-06-05 00:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "job",
            "0011_rename_revenue_adjustment_adjustmententry_price_adjustment_and_more",
        ),
        ("job", "0011_update_purchase_order_line_reference"),
    ]

    operations = []
