# Generated by Django 5.2 on 2025-06-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "job",
            "0011_rename_revenue_adjustment_adjustmententry_price_adjustment_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobevent",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="job.job",
            ),
        ),
    ]
