# Generated by Django 5.2 on 2025-06-05 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0012_alter_jobevent_job"),
        ("job", "0012_merge_20250604_2123"),
    ]

    operations = []
