# Generated by Django 5.2 on 2025-06-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0013_merge_20250605_0811"),
    ]

    operations = [
        # No operations needed - JobPart table is now created with correct name from the start
    ]
