# Generated by Django 5.2 on 2025-06-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_clientcontact"),
        ("job", "0015_alter_historicaljob_client_alter_job_client_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The contact person for this job",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="client.clientcontact",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                help_text="The contact person for this job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="client.clientcontact",
            ),
        ),
    ]
