# Generated by Django 5.2 on 2025-06-09 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0017_migrate_contact_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustmententry",
            name="accounting_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date for accounting purposes (when the adjustment was made)",
            ),
        ),
        migrations.AddField(
            model_name="materialentry",
            name="accounting_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Date for accounting purposes (when the material was used)",
            ),
        ),
    ]
