# Generated by Django 5.2 on 2025-06-09 21:04

from django.db import migrations


def populate_accounting_dates(apps, schema_editor):
    """Populate accounting_date from created_at for existing records"""
    MaterialEntry = apps.get_model('job', 'MaterialEntry')
    AdjustmentEntry = apps.get_model('job', 'AdjustmentEntry')
    
    # Update MaterialEntry records
    for entry in MaterialEntry.objects.all():
        entry.accounting_date = entry.created_at.date()
        entry.save(update_fields=['accounting_date'])
    
    # Update AdjustmentEntry records
    for entry in AdjustmentEntry.objects.all():
        entry.accounting_date = entry.created_at.date()
        entry.save(update_fields=['accounting_date'])


def reverse_populate_accounting_dates(apps, schema_editor):
    """Reverse function does nothing as we can't reverse this operation"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0018_add_accounting_date_fields"),
    ]

    operations = [
        migrations.RunPython(
            populate_accounting_dates,
            reverse_populate_accounting_dates,
        ),
    ]
