# Generated by Django 5.2 on 2025-06-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_costing_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='latest_actual',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Latest actual cost set snapshot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.costset'),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='latest_estimate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Latest estimate cost set snapshot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.costset'),
        ),
        migrations.AddField(
            model_name='historicaljob',
            name='latest_quote',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Latest quote cost set snapshot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.costset'),
        ),
        migrations.AddField(
            model_name='job',
            name='latest_actual',
            field=models.OneToOneField(blank=True, help_text='Latest actual cost set snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='job.costset'),
        ),
        migrations.AddField(
            model_name='job',
            name='latest_estimate',
            field=models.OneToOneField(blank=True, help_text='Latest estimate cost set snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='job.costset'),
        ),
        migrations.AddField(
            model_name='job',
            name='latest_quote',
            field=models.OneToOneField(blank=True, help_text='Latest quote cost set snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='job.costset'),
        ),
    ]
