# Generated by Django 5.2 on 2025-06-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0019_populate_accounting_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="priority",
            field=models.FloatField(
                default=0.0,
                help_text="Priority of the job, higher numbers are higher priority.",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="priority",
            field=models.FloatField(
                default=0.0,
                help_text="Priority of the job, higher numbers are higher priority.",
            ),
        ),
    ]
