# Generated by Django 5.2 on 2025-06-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0020_change_priority_to_float"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustmententry",
            name="is_quote_adjustment",
            field=models.BooleanField(
                default=False,
                help_text="True if this adjustment was automatically created to match quoted revenue",
            ),
        ),
    ]
