# Generated by Django 5.2 on 2025-06-15 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0019_job_latest_sets"),
        ("job", "0021_add_is_quote_adjustment_field"),
    ]

    operations = []
