# Generated by Django 5.2 on 2025-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0025_update_job_statuses_for_kanban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="status",
            field=models.CharField(
                choices=[
                    ("quoting", "Quoting"),
                    ("accepted_quote", "Accepted Quote"),
                    ("awaiting_materials", "Awaiting Materials"),
                    ("awaiting_staff", "Awaiting Staff"),
                    ("awaiting_site_availability", "Awaiting Site Availability"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("special", "Special"),
                    ("recently_completed", "Recently Completed"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="quoting",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("quoting", "Quoting"),
                    ("accepted_quote", "Accepted Quote"),
                    ("awaiting_materials", "Awaiting Materials"),
                    ("awaiting_staff", "Awaiting Staff"),
                    ("awaiting_site_availability", "Awaiting Site Availability"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("special", "Special"),
                    ("recently_completed", "Recently Completed"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="quoting",
                max_length=30,
            ),
        ),
    ]
