# Generated by Django 5.2 on 2025-06-02 08:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workflow", "0151_remove_purchaseline_purchase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=500)),
                (
                    "item_no",
                    models.CharField(
                        help_text="Supplier's item/SKU number", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("specifications", models.TextField(blank=True, null=True)),
                (
                    "variant_id",
                    models.CharField(
                        help_text="Unique variant identifier from supplier",
                        max_length=100,
                    ),
                ),
                (
                    "variant_width",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "variant_length",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "variant_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'per metre', 'each'",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("variant_available_stock", models.IntegerField(blank=True, null=True)),
                (
                    "url",
                    models.URLField(
                        help_text="Direct URL to this product on supplier's website",
                        max_length=1000,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_products",
                        to="workflow.client",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["variant_id"], name="quoting_sup_variant_948a79_idx"
                    ),
                    models.Index(
                        fields=["product_name"], name="quoting_sup_product_d21402_idx"
                    ),
                ],
                "unique_together": {("supplier", "variant_id")},
            },
        ),
    ]
