# Generated by Django 5.2 on 2025-06-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
        ("quoting", "0002_supplierpricelist_supplierproduct_price_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierpricelist",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_lists",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="supplierproduct",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scraped_products",
                to="client.client",
            ),
        ),
    ]
