# Generated by Django 5.2 on 2025-06-10 05:10

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_clientcontact"),
        ("quoting", "0003_alter_supplierpricelist_supplier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("products_scraped", models.IntegerField(default=0)),
                ("products_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_jobs",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scrape Job",
                "verbose_name_plural": "Scrape Jobs",
                "ordering": ["-started_at"],
            },
        ),
    ]
