# Generated by Django 5.2 on 2025-06-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_populate_merge_fields"),
        ("quoting", "0004_scrapejob"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplierproduct",
            unique_together={("supplier", "item_no", "variant_id")},
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["item_no"], name="quoting_sup_item_no_c2e6f6_idx"
            ),
        ),
    ]
