# Generated by Django 5.2 on 2025-06-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_populate_merge_fields"),
        ("quoting", "0005_alter_supplierproduct_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="supplierproduct",
            unique_together={("supplier", "url", "item_no", "variant_id")},
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(fields=["url"], name="quoting_sup_url_2d3c4a_idx"),
        ),
    ]
