# Generated by Django 5.2 on 2025-06-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0007_supplierproduct_parsed_alloy_and_more"),
    ]

    operations = []
