# Generated by Django 5.2 on 2025-06-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0009_productparsingmapping_derived_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="productparsingmapping",
            name="item_code_is_in_xero",
            field=models.BooleanField(
                default=False,
                help_text="Whether the mapped item code exists in Xero inventory (Stock model)",
            ),
        ),
    ]
