# Generated by Django 5.2 on 2025-06-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoting", "0010_productparsingmapping_item_code_is_in_xero"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="mapping_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash linking to ProductParsingMapping for this product",
                max_length=64,
                null=True,
            ),
        ),
    ]
