# Generated by Django 5.0.6 on 2024-09-14 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adjustmententry",
            name="job_pricing_type",
        ),
        migrations.RemoveField(
            model_name="materialentry",
            name="job_pricing_type",
        ),
        migrations.RenameField(
            model_name="materialentry",
            old_name="cost_price",
            new_name="unit_cost",
        ),
        migrations.RenameField(
            model_name="materialentry",
            old_name="sale_price",
            new_name="unit_revenue",
        ),
        migrations.RemoveField(
            model_name="timeentry",
            name="job",
        ),
        migrations.CreateModel(
            name="JobPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pricing_stage",
                    models.CharField(
                        choices=[
                            ("fixed_price", "Fixed Price"),
                            ("time_materials", "Time & Materials"),
                        ],
                        default="time_materials",
                        help_text="Type of estimate for the job pricing.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricings",
                        to="workflow.job",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adjustmententry",
            name="job_pricing",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustment_entries",
                to="workflow.jobpricing",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materialentry",
            name="job_pricing",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_entries",
                to="workflow.jobpricing",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="job_pricing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="workflow.jobpricing",
            ),
        ),
        migrations.DeleteModel(
            name="JobPricingType",
        ),
    ]
