# Generated by Django 5.0.6 on 2024-09-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0003_alter_jobpricing_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpricing",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("fixed_price", "Fixed Price"),
                    ("time_materials", "Time & Materials"),
                ],
                default="time_materials",
                help_text="Type of pricing for the job (fixed price or time and materials).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobpricing",
            name="pricing_stage",
            field=models.CharField(
                choices=[
                    ("estimate", "Estimate"),
                    ("quote", "Quote"),
                    ("reality", "Reality"),
                ],
                default="estimate",
                help_text="Stage of the job pricing (estimate, quote, or reality).",
                max_length=20,
            ),
        ),
    ]
