# Generated by Django 5.0.6 on 2024-09-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0004_jobpricing_pricing_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="job_number",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_number",
            field=models.IntegerField(unique=True),
        ),
    ]
