# Generated by Django 5.0.6 on 2024-09-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_quotepricing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="client_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="client_name",
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="client",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workflow.client",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="workflow.client",
            ),
        ),
    ]
