# Generated by Django 5.0.6 on 2024-09-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_quotepricing"),
    ]

    operations = [
    ]
