# Generated by Django 5.0.6 on 2024-09-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_remove_historicaljob_client_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpricing",
            name="job_pricing_number",
        ),
    ]
