# Generated by Django 5.0.6 on 2024-09-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
