# Generated by Django 5.0.6 on 2024-09-17 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_client_raw_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("xero_invoice_id", models.UUIDField(unique=True)),
                ("invoice_number", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("due_date", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("last_modified", models.DateTimeField()),
                ("raw_json", models.JSONField()),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="workflow.client",
                    ),
                ),
            ],
        ),
    ]
