# Generated by Django 5.0.6 on 2024-10-01 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_historicaljob_job_is_valid_job_job_is_valid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="job_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="job_name",
        ),
    ]
