# Generated by Django 5.0.6 on 2024-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0010_remove_historicaljob_job_name_remove_job_job_name"),
    ]

    operations = [
    ]
