# Generated by Django 5.0.6 on 2024-10-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0010_remove_historicaljob_job_name_remove_job_job_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeentry",
            name="minutes",
        ),
        migrations.AddField(
            model_name="timeentry",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="items",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="timeentry",
            name="mins_per_item",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
