# Generated by Django 5.0.6 on 2024-09-17 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0011_bill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"verbose_name": "Bill", "verbose_name_plural": "Bills"},
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"verbose_name": "Invoice", "verbose_name_plural": "Invoices"},
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="bill_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="xero_bill_id",
            new_name="xero_id",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="invoice_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="xero_invoice_id",
            new_name="xero_id",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="vendor",
        ),
        migrations.AddField(
            model_name="bill",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflow.client",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bill",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workflow.client"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
