# Generated by Django 5.0.6 on 2024-10-01 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0011_remove_timeentry_minutes_timeentry_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
