# Generated by Django 5.0.6 on 2024-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0013_alter_timeentry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="quote_acceptance_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="quote_acceptance_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
