# Generated by Django 5.0.6 on 2024-10-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0014_historicaljob_quote_acceptance_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
