# Generated by Django 5.0.6 on 2024-10-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0015_historicaljob_delivery_date_job_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialentry",
            name="item_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
