# Generated by Django 5.0.6 on 2024-10-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0017_materialentry_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adjustmententry",
            old_name="cost",
            new_name="cost_adjustment",
        ),
        migrations.RenameField(
            model_name="adjustmententry",
            old_name="revenue",
            new_name="price_adjustment",
        ),
        migrations.AddField(
            model_name="adjustmententry",
            name="comments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
