# Generated by Django 5.0.6 on 2024-11-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0018_rename_cost_adjustmententry_cost_adjustment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
