# Generated by Django 5.0.6 on 2024-11-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0020_historicaljob_material_gauge_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
