# Generated by Django 5.0.6 on 2024-11-06 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0024_alter_jobpricing_options_jobpricing_revision_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="latest_estimate_pricing",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workflow.jobpricing",
            ),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="latest_quote_pricing",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workflow.jobpricing",
            ),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="latest_reality_pricing",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workflow.jobpricing",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="archived_pricings",
            field=models.ManyToManyField(
                blank=True,
                related_name="archived_pricings_for_job",
                to="workflow.jobpricing",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="latest_estimate_pricing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_estimate_for_job",
                to="workflow.jobpricing",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="latest_quote_pricing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_quote_for_job",
                to="workflow.jobpricing",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="latest_reality_pricing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="latest_reality_for_job",
                to="workflow.jobpricing",
            ),
        ),
    ]
