# Generated by Django 5.0.6 on 2024-11-16 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0031_alter_jobpricing_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="latest_estimate_pricing",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_estimate_for_job",
                to="workflow.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="latest_quote_pricing",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_quote_for_job",
                to="workflow.jobpricing",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="latest_reality_pricing",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="latest_reality_for_job",
                to="workflow.jobpricing",
            ),
        ),
    ]
