# Generated by Django 5.0.6 on 2024-11-16 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0032_alter_job_latest_estimate_pricing_and_more"),
    ]

    operations = [
    ]
