# Generated by Django 5.0.6 on 2024-11-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0033_remove_jobpricing_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialentry",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="materialentry",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="materialentry",
            name="unit_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
