# Generated by Django 5.0.6 on 2024-11-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0035_alter_adjustmententry_comments_and_more"),
    ]

    operations = []
