# Generated by Django 5.0.6 on 2024-11-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0035_alter_adjustmententry_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="hours_fri",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Friday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="hours_mon",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Monday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="hours_sat",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Standard hours for Saturday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="hours_sun",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Standard hours for Sunday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="hours_thu",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Thursday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="hours_tue",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Tuesday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="hours_wed",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Wednesday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="historicalstaff",
            name="raw_ims_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="hours_fri",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Friday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="hours_mon",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Monday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="hours_sat",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Standard hours for Saturday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="hours_sun",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Standard hours for Sunday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="hours_thu",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Thursday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="hours_tue",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Tuesday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="hours_wed",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Standard hours for Wednesday, 0 for non-working day",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="raw_ims_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
