# Generated by Django 5.0.6 on 2024-11-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow",
            "0036_historicalstaff_hours_fri_historicalstaff_hours_mon_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstaff",
            name="charge_out_rate",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="charge_out_rate",
        ),
        migrations.AlterField(
            model_name="historicalstaff",
            name="wage_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="staff",
            name="wage_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
