# Generated by Django 5.0.6 on 2024-11-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0037_remove_historicalstaff_charge_out_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="shop_job",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="shop_job",
            field=models.BooleanField(default=False),
        ),
    ]
