# Generated by Django 5.0.6 on 2024-11-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0040_alter_historicaljob_charge_out_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="wage_rate_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                help_text="Set to 2 for double time, etc.  Do not set to 0 unless you want the staff member to work for free.",
                max_digits=5,
            ),
        ),
    ]
