# Generated by Django 5.0.6 on 2024-11-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0044_remove_timeentry_mins_per_item_timeentry_hours_and_more"),
    ]

    operations = []