# Generated by Django 5.0.6 on 2024-11-22 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0049_companydefaults_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaff",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="staff",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
