# Generated by Django 5.0.6 on 2024-11-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0051_alter_historicalstaff_updated_at_and_more"),
    ]

    operations = []
