# Generated by Django 5.0.6 on 2024-11-22 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0051_alter_historicalstaff_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpricing",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricings",
                to="workflow.job",
            ),
        ),
    ]
