# Generated by Django 5.0.6 on 2024-11-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0054_remove_historicaljob_shop_job_remove_job_shop_job_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="This becomes the first line item on the invoice",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="material_gauge_quantity",
            field=models.TextField(
                blank=True,
                help_text="Internal notes such as the material to use.  Not shown on the invoice",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="This becomes the first line item on the invoice",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="material_gauge_quantity",
            field=models.TextField(
                blank=True,
                help_text="Internal notes such as the material to use.  Not shown on the invoice",
                null=True,
            ),
        ),
    ]
