# Generated by Django 5.0.6 on 2024-11-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0055_alter_historicaljob_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="total",
            new_name="total_excl_tax",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="total",
            new_name="total_excl_tax",
        ),
        migrations.RenameField(
            model_name="invoicelineitem",
            old_name="line_amount",
            new_name="line_amount_excl_tax",
        ),
        migrations.AddField(
            model_name="bill",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bill",
            name="total_incl_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_incl_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="line_amount_incl_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
