# Generated by Django 5.0.6 on 2024-11-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0056_rename_total_bill_total_excl_tax_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billlineitem",
            old_name="line_amount",
            new_name="line_amount_excl_tax",
        ),
        migrations.RemoveField(
            model_name="invoicelineitem",
            name="tax",
        ),
        migrations.AddField(
            model_name="billlineitem",
            name="line_amount_incl_tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
