# Generated by Django 5.0.6 on 2024-12-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0058_alter_billlineitem_options_and_more"),
    ]

    operations = [
    ]
