# Generated by Django 5.0.6 on 2024-12-06 19:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0059_rename_creditlineitem_creditnotelineitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="XeroJournal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                ("date", models.DateField()),
                ("created_date_utc", models.DateTimeField()),
                ("journal_number", models.IntegerField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=255, null=True)),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("source_type", models.CharField(blank=True, max_length=50, null=True)),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="XeroJournalLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_line_id", models.UUIDField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax_type", models.CharField(blank=True, max_length=50, null=True)),
                ("tax_name", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workflow.xeroaccount",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="workflow.xerojournal",
                    ),
                ),
            ],
        ),
    ]
