# Generated by Django 5.0.6 on 2024-12-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0062_xerojournal_xero_last_modified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="xerojournal",
            old_name="date",
            new_name="journal_date",
        ),
    ]
