# Generated by Django 5.1.4 on 2025-01-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0066_jobfile"),
    ]

    operations = [
    ]
