# Generated by Django 5.1.4 on 2025-01-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0066_jobfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfile",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("deleted", "Deleted")],
                default="active",
                max_length=20,
            ),
        ),
    ]
