# Generated by Django 5.1.4 on 2025-01-02 06:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0067_supplier_purchase_purchaseline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseline",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="workflow.purchase",
            ),
        ),
    ]
