# Generated by Django 5.1.4 on 2025-01-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0068_jobevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobevent",
            old_name="user",
            new_name="staff",
        ),
    ]
