# Generated by Django 5.1.4 on 2025-01-11 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0070_jobevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobevent",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
