# Generated by Django 5.1.4 on 2025-01-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0070_jobevent_event_type"),
    ]

    operations = [
    ]
