# Generated by Django 5.1.5 on 2025-02-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0075_jobfile_print_on_jobsheet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpricing",
            name="pricing_methodology",
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="pricing_methodology",
            field=models.CharField(
                choices=[
                    ("fixed_price", "Fixed Price"),
                    ("time_materials", "Time & Materials"),
                ],
                default="time_materials",
                help_text="Type of pricing for the job (fixed price or time and materials).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="pricing_methodology",
            field=models.CharField(
                choices=[
                    ("fixed_price", "Fixed Price"),
                    ("time_materials", "Time & Materials"),
                ],
                default="time_materials",
                help_text="Type of pricing for the job (fixed price or time and materials).",
                max_length=20,
            ),
        ),
    ]
