# Generated by Django 5.1.4 on 2025-02-03 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0075_invoice_online_url_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="workflow.job",
            ),
        ),
    ]
