# Generated by Django 5.1.5 on 2025-02-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0075_jobfile_print_on_jobsheet"),
    ]

    operations = [
    ]
