# Generated by Django 5.1.5 on 2025-02-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0075_jobfile_print_on_jobsheet"),
    ]

    operations = [
        # No operations needed - Job models have been moved to job app
    ]
