# Generated by Django 5.1.4 on 2025-02-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0076_invoice_job"),
    ]

    operations = [
    ]
