# Generated by Django 5.1.4 on 2025-02-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0077_alter_quote_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quote",
                to="workflow.job",
            ),
        ),
    ]
