# Generated by Django 5.1.5 on 2025-02-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0076_remove_jobpricing_pricing_type_and_more"),
        ("workflow", "0078_alter_quote_job"),
    ]

    operations = []
