# Generated by Django 5.1.5 on 2025-02-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0076_1_rename_job_pricing_stage_to_pricing_type"),
        ("workflow", "0078_alter_quote_job"),
    ]

    operations = []
