# Generated by Django 5.1.5 on 2025-02-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0079_merge_20250207_1950"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="material_gauge_quantity",
            field=models.TextField(
                blank=True,
                help_text="Internal notes such as the material to use. Not shown on the invoice",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="material_gauge_quantity",
            field=models.TextField(
                blank=True,
                help_text="Internal notes such as the material to use. Not shown on the invoice",
                null=True,
            ),
        ),
    ]