# Generated by Django 5.1.5 on 2025-03-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0086_alter_historicaljob_contact_person_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="is_primary",
            field=models.BooleanField(default=True, unique=True),
        ),
    ]
