# Generated by Django 5.1.5 on 2025-03-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0080_alter_historicaljob_material_gauge_quantity_and_more"),
        ("workflow", "0087_companydefaults_is_primary"),
    ]

    operations = []