# Generated by Django 5.1.5 on 2025-03-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0088_merge_20250305_0549"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="coolected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="coolected",
            field=models.BooleanField(default=False),
        ),
    ]
