# Generated by Django 5.1.5 on 2025-03-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0089_companydefaults_starting_job_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="password_needs_reset",
            field=models.BooleanField(default=False),
        ),
    ]
