# Generated by Django 5.1.5 on 2025-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0089_historicaljob_coolected_job_coolected"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="starting_job_number",
            field=models.IntegerField(
                default=1,
                help_text="Helper field to set the starting job number based on the latest paper job",
            ),
        ),
    ]
