# Generated by Django 5.1.5 on 2025-03-10 07:15

from django.db import migrations, models
from django.db.models import F
import sys


def add_collected_if_missing(apps, schema_editor):
    """Add the collected column if coolected doesn't exist"""
    # Get the historical model
    db_alias = schema_editor.connection.alias
    HistoricalJob = apps.get_model("workflow", "HistoricalJob")
    Job = apps.get_model("workflow", "Job")
    
    # Check if the column exists using raw SQL
    cursor = schema_editor.connection.cursor()
    
    # For HistoricalJob table
    try:
        cursor.execute(
            f"SELECT coolected FROM {HistoricalJob._meta.db_table} LIMIT 1"
        )
    except Exception as e:
        # If coolected doesn't exist, add collected directly
        print(f"Adding collected field to HistoricalJob: {e}", file=sys.stderr)
        schema_editor.add_field(
            HistoricalJob,
            models.BooleanField(default=False, name="collected")
        )
    else:
        # If coolected exists, rename it to collected
        print(f"Renaming coolected to collected in HistoricalJob", file=sys.stderr)
        schema_editor.alter_field(
            HistoricalJob,
            HistoricalJob._meta.get_field("coolected"),
            HistoricalJob._meta.get_field("collected"),
        )
        
    # For Job table
    try:
        cursor.execute(
            f"SELECT coolected FROM {Job._meta.db_table} LIMIT 1"
        )
    except Exception as e:
        # If coolected doesn't exist, add collected directly
        print(f"Adding collected field to Job: {e}", file=sys.stderr)
        schema_editor.add_field(
            Job,
            models.BooleanField(default=False, name="collected")
        )
    else:
        # If coolected exists, rename it to collected
        print(f"Renaming coolected to collected in Job", file=sys.stderr)
        schema_editor.alter_field(
            Job,
            Job._meta.get_field("coolected"),
            Job._meta.get_field("collected"),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0089_historicaljob_coolected_job_coolected'),
    ]

    operations = [
        migrations.RunPython(add_collected_if_missing),
    ]
