# Generated by Django 5.1.5 on 2025-03-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0090_companydefaults_starting_job_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaljob",
            old_name="coolected",
            new_name="collected",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="coolected",
            new_name="collected",
        ),
    ]
