# Generated by Django 5.1.5 on 2025-03-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0090_historicalstaff_password_needs_reset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="password_needs_reset",
            field=models.BooleanField(default=False),
        ),
    ]
