# Generated by Django 5.1.5 on 2025-03-10 07:15

from django.db import migrations, models
from django.db.models import F
import sys


def add_collected_if_missing(apps, schema_editor):
    """Add the collected column if coolected doesn't exist"""
    # Get the historical model
    db_alias = schema_editor.connection.alias
    HistoricalJob = apps.get_model("workflow", "HistoricalJob")
    Job = apps.get_model("workflow", "Job")
    
    # Check if the column exists using raw SQL
    cursor = schema_editor.connection.cursor()
    
    # Migration has already been applied
    print("Migration 0090 is actually a no-op since 0089 already adds the 'collected' field.")
    print("Skipping the actual field operations to avoid conflicts.")

    # The original code had bugs in the add_field calls and is no longer needed
    # since migration 0089 already adds the 'collected' field to both models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0090_alter_staff_options'),
    ]

    operations = [
        migrations.RunPython(add_collected_if_missing, migrations.RunPython.noop),
    ]
