# Generated by Django 5.1.5 on 2025-03-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0091_add_password_needs_reset_historicalstaff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaljob",
            old_name="coolected",
            new_name="collected",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="coolected",
            new_name="collected",
        ),
    ]
