# Generated by Django 5.1.5 on 2025-03-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0091_rename_coolected_historicaljob_collected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalstaff",
            name="password_needs_reset",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="staff",
            name="password_needs_reset",
            field=models.BooleanField(default=False),
        ),
    ]
