# Generated by Django 5.1.5 on 2025-03-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0092_historicalstaff_password_needs_reset_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalstaff",
            name="password_needs_reset",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="password_needs_reset",
        ),
    ]
