# Generated by Django 5.1.5 on 2025-03-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0091_rename_coolected_historicaljob_collected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about the job. Not shown on the invoice.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about the job. Not shown on the invoice.",
                null=True,
            ),
        ),
    ]
