# Generated by Django 5.1.5 on 2025-03-09 21:06

from django.db import migrations


def migrate_material_gauge_to_notes(apps, schema_editor):
    Job = apps.get_model('workflow', 'Job')
    for job in Job.objects.all():
        if job.material_gauge_quantity and job.material_gauge_quantity.strip():
            # Prepare formatted content for Quill
            material_content = f"<h3>Material / Gauge / Quantity</h3><p>{job.material_gauge_quantity}</p>"
            
            # Add to existing notes (if any) or create new content
            if job.notes and job.notes.strip():
                job.notes = material_content + "<p><br></p>" + job.notes
            else:
                job.notes = material_content
                
            job.material_gauge_quantity = ""  # Clear original field
            job.save()


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0093_historicaljob_notes_job_notes"),
    ]

    operations = [
        migrations.RunPython(migrate_material_gauge_to_notes, reverse_code=migrations.RunPython.noop),
    ]
