# Generated by Django 5.1.5 on 2025-03-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0094_register_existing_password_needs_reset_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="collected",
        ),
        migrations.RemoveField(
            model_name="job",
            name="collected",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="password_needs_reset",
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="coolected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="coolected",
            field=models.BooleanField(default=False),
        ),
    ]
