# Generated by Django 5.1.5 on 2025-03-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0094_migrate_material_gauge_to_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="material_gauge_quantity",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED - Use notes field instead. Content will be automatically migrated.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="material_gauge_quantity",
            field=models.TextField(
                blank=True,
                help_text="DEPRECATED - Use notes field instead. Content will be automatically migrated.",
                null=True,
            ),
        ),
    ]
