# Generated by Django 5.1.5 on 2025-03-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow",
            "0095_remove_historicaljob_collected_remove_job_collected_and_more",
        ),
    ]

    operations = []
