# Generated by Django 5.1.5 on 2025-03-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0096_merge_20250310_2039"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaff",
            name="ims_payroll_id",
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="ims_payroll_id",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
