# Generated by Django 5.1.5 on 2025-03-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0096_merge_20250310_2039"),
    ]

    operations = [
        # Staff models moved to accounts app - these changes are already there
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[],
        ),
    ]
