# Generated by Django 5.1.5 on 2025-03-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0097_alter_historicalstaff_ims_payroll_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstaff",
            name="ims_payroll_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="ims_payroll_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
