# Generated by Django 5.1.5 on 2025-03-15 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0098_alter_historicalstaff_ims_payroll_id_and_more"),
    ]

    operations = []
