# Generated by Django 5.1.5 on 2025-03-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0101_merge_20250317_1527"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="The job this purchase line is for",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_lines",
                to="workflow.job",
            ),
        ),
    ]
