# Generated by Django 5.1.5 on 2025-03-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0101_merge_20250317_1527"),
        ("workflow", "0101_merge_20250317_1858"),
    ]

    operations = []
