# Generated by Django 5.1.5 on 2025-03-23 03:40
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0101_merge_20250317_1527"),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='xero_last_synced',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='xero_last_synced',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
