# Generated by Django 5.1.5 on 2025-03-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0105_add_xero_fields_to_purchase_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="price_tbc",
            field=models.BooleanField(
                default=False,
                help_text="If true, the price is to be confirmed and unit cost will be None",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="unit_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
