# Generated by Django 5.1.5 on 2025-03-27 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0108_xeroaccount_xero_last_synced"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description of the stock item", max_length=255
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current quantity of the stock item",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per unit of the stock item",
                        max_digits=10,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date the stock item was created",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("purchase_order", "Purchase Order"),
                            ("split", "Split from another stock item"),
                            ("manual", "Manual Entry"),
                        ],
                        help_text="Source of the stock item",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        help_text="ID of the source item (e.g., PO number)",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the stock item"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="The job this stock item is assigned to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_items",
                        to="workflow.job",
                    ),
                ),
            ],
        ),
    ]
