# Generated by Django 5.1.5 on 2025-03-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0108_xeroaccount_xero_last_synced"),
    ]

    operations = [
    ]
