# Generated by Django 5.1.5 on 2025-03-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0110_purchaseorder_reference"),
    ]

    operations = [
    ]
