# Generated by Django 5.1.5 on 2025-04-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0110_purchaseorder_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="minutes_per_item",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
