# Generated by Django 5.1.5 on 2025-03-31 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0111_remove_purchaseline_purchase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="source_id",
        ),
        migrations.AddField(
            model_name="materialentry",
            name="source_stock",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stock item consumed to create this entry",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumed_entries",
                to="workflow.stock",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="source_parent_stock",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent stock item this was split from (if source='split_from_stock')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_stock_splits",
                to="workflow.stock",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="source_purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The PO line this stock originated from (if source='purchase_order')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_generated",
                to="workflow.purchaseorderline",
            ),
        ),
        migrations.AlterField(
            model_name="materialentry",
            name="purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Convenience link to original PO line (derived via source_stock)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_entries",
                to="workflow.purchaseorderline",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="source",
            field=models.CharField(
                choices=[
                    ("purchase_order", "Purchase Order Receipt"),
                    ("split_from_stock", "Split/Offcut from Stock"),
                    ("manual", "Manual Adjustment/Stocktake"),
                ],
                help_text="Origin of this stock item",
                max_length=50,
            ),
        ),
    ]
