# Generated by Django 5.1.5 on 2025-03-31 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0111_alter_timeentry_minutes_per_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseline",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="purchaseline",
            name="po_line",
        ),
        migrations.RemoveField(
            model_name="materialentry",
            name="purchase_line",
        ),
        migrations.AddField(
            model_name="materialentry",
            name="purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Source purchase order line if created from a PO receipt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="material_entries",
                to="workflow.purchaseorderline",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="po_lines",
                to="workflow.purchaseorder",
            ),
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.DeleteModel(
            name="PurchaseLine",
        ),
    ]
