# Generated by Django 5.1.5 on 2025-04-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0111_remove_purchaseline_purchase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="minutes_per_item",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
