# Generated by Django 5.1.5 on 2025-04-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0113_remove_stock_source_id_materialentry_source_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False when quantity reaches zero or item is fully consumed/transformed",
            ),
        ),
    ]
