# Generated by Django 5.1.5 on 2025-03-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0114_stock_is_active"),
    ]

    operations = [
    ]
