# Generated by Django 5.1.5 on 2025-04-03 07:36

import uuid
import django.utils.timezone
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0114_stock_is_active"),
    ]

    operations = [

        
        # 1. Delete related MaterialEntry records
        migrations.RunSQL(
            "UPDATE workflow_materialentry SET source_stock_id = NULL WHERE source_stock_id IS NOT NULL;"
        ),

        # 2. Delete all existing stock records
        migrations.RunSQL(
            "DELETE FROM workflow_stock;"
        ),

        # 3. Drop the old table and create a new one with UUID primary key
        migrations.RunSQL(
            "DROP TABLE workflow_stock;"
        ),
        
        # 4. Create a new Stock model with UUID primary key
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)),
                ("description", models.CharField(help_text="Description of the stock item", max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, help_text="Current quantity of the stock item", max_digits=10)),
                ("unit_cost", models.DecimalField(decimal_places=2, help_text="Cost per unit of the stock item", max_digits=10)),
                ("date", models.DateTimeField(default=django.utils.timezone.now, help_text="Date the stock item was created")),
                ("source", models.CharField(choices=[("purchase_order", "Purchase Order Receipt"), ("split_from_stock", "Split/Offcut from Stock"), ("manual", "Manual Adjustment/Stocktake")], help_text="Origin of this stock item", max_length=50)),
                ("notes", models.TextField(blank=True, help_text="Additional notes about the stock item")),
                ("is_active", models.BooleanField(db_index=True, default=True, help_text="False when quantity reaches zero or item is fully consumed/transformed")),
                ("job", models.ForeignKey(blank=True, help_text="The job this stock item is assigned to", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_items", to="workflow.job")),
                ("source_parent_stock", models.ForeignKey(blank=True, help_text="The parent stock item this was split from (if source='split_from_stock')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="child_stock_splits", to="workflow.stock")),
                ("source_purchase_order_line", models.ForeignKey(blank=True, help_text="The PO line this stock originated from (if source='purchase_order')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="stock_generated", to="workflow.purchaseorderline")),
            ],
        ),
    ]
