# Generated by Django 5.1.5 on 2025-04-03 08:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0115_alter_stock_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="alloy",
            field=models.CharField(
                blank=True,
                help_text="Alloy specification (e.g., 304, 6061)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="location",
            field=models.TextField(blank=True, help_text="Where we are keeping this"),
        ),
        migrations.AddField(
            model_name="stock",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminum", "Aluminum"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("other", "Other"),
                ],
                default="other",
                help_text="Type of metal",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="specifics",
            field=models.CharField(
                blank=True,
                help_text="Specific details (e.g., m8 countersunk socket screw)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
