# Generated by Django 5.1.5 on 2025-04-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0116_stock_alloy_stock_location_stock_metal_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminum", "Aluminum"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                default="unspecified",
                help_text="Type of metal",
                max_length=100,
            ),
        ),
    ]
