# Generated by Django 5.1.5 on 2025-03-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0118_alter_materialentry_source_stock"),
    ]

    operations = [
    ]
