# Generated by Django 5.1.5 on 2025-04-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0118_alter_materialentry_source_stock"),
    ]

    # To fix django.db.utils.DataError: (1265, "Data truncated for column 'source_stock_id' at row 1")      
    # When adding stock to a job
    operations = [
        migrations.AlterField(
            model_name='materialentry',
            name='source_stock',
            field=models.ForeignKey(
                'Stock',
                on_delete=models.PROTECT,
                null=True,
                blank=True,
                related_name='consumed_entries',
                help_text="The Stock item consumed to create this entry"
            ),
        ),
        migrations.RunSQL(
            "ALTER TABLE workflow_materialentry MODIFY COLUMN source_stock_id CHAR(36);"
        ),
    ]
