# Generated by Django 5.1.5 on 2025-04-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0120_add_purchase_order_deleted_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="alloy",
            field=models.CharField(
                blank=True,
                help_text="Alloy specification (e.g., 304, 6061)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Where this item will be stored",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminum", "Aluminum"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                default="unspecified",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="specifics",
            field=models.CharField(
                blank=True,
                help_text="Specific detals (e.g., m8 countersunk socket screw)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="materialentry",
            name="source_stock",
            field=models.ForeignKey(
                blank=True,
                help_text="The Stock item consumed to create this entry",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumed_entries",
                to="workflow.stock",
            ),
        ),
    ]
