# Generated by Django 5.1.5 on 2025-04-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0120_add_purchase_order_deleted_status"),
    ]

    operations = [
    ]
