# Generated by Django 5.2 on 2025-04-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workflow",
            "0121_purchaseorderline_alloy_purchaseorderline_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="billable_threshold_amber",
            field=models.DecimalField(
                decimal_places=2,
                default=30.0,
                help_text="Daily billable hours between this threshold and the green threshold are marked in amber",
                max_digits=5,
                verbose_name="Amber Threshold of Billable Hours",
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="billable_threshold_green",
            field=models.DecimalField(
                decimal_places=2,
                default=45.0,
                help_text="Daily billable hours above this threshold are marked in green",
                max_digits=5,
                verbose_name="Green Threshold of Billable Hours",
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="daily_gp_target",
            field=models.DecimalField(
                decimal_places=2,
                default=2500.0,
                help_text="Daily gross profit goal in dolars",
                max_digits=10,
                verbose_name="Daily Goal of Gross Profit",
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="shop_hours_target_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Target percentage of hours worked in shop jobs",
                max_digits=5,
                verbose_name="Hours percentage goal in Shop Jobs",
            ),
        ),
    ]
