# Generated by Django 5.1.5 on 2025-04-20 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0124_normalize_po_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
