# Generated by Django 5.2 on 2025-04-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0126_alter_purchaseorder_order_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="raw_json",
        ),
        migrations.RemoveField(
            model_name="purchaseorderline",
            name="item_code",
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="dimensions",
            field=models.CharField(
                blank=True,
                help_text="Dimensions such as length, width, height, etc.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="supplier_item_code",
            field=models.CharField(
                blank=True,
                help_text="Supplier's own item code/SKU",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="companydefaults",
            name="daily_gp_target",
            field=models.DecimalField(
                decimal_places=2,
                default=1250.0,
                help_text="Daily gross profit goal in dolars",
                max_digits=10,
                verbose_name="Daily Goal of Gross Profit",
            ),
        ),
    ]
