# Generated by Django 5.2 on 2025-04-22 01:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0127_remove_purchaseorder_raw_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="retail_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.2"),
                help_text="Retail markup rate for this stock item (e.g., 0.2 for 20%)",
                max_digits=10,
            ),
        ),
    ]
