# Generated by Django 5.2 on 2025-04-28 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0128_stock_retail_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="gemini_api_key",
            field=models.CharField(
                blank=True,
                help_text="API key for Google Gemini LLM",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="The job this stock item is assigned to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="workflow.job",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="source_purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The PO line this stock originated from (if source='purchase_order')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_generated",
                to="workflow.purchaseorderline",
            ),
        ),
    ]
