# Generated by Django 5.2 on 2025-04-28 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0128_stock_retail_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="gemini_api_key",
            field=models.CharField(
                blank=True,
                help_text="API key for Google Gemini LLM",
                max_length=255,
                null=True,
            ),
        )
    ]
