# Generated by Django 5.2 on 2025-05-08 23:12

from django.db import migrations


def convert_approved_to_accepted_quote(apps, schema_editor):
    # Get the historical model
    Job = apps.get_model('workflow', 'Job')
    
    # Update all jobs with status 'approved' to 'accepted_quote'
    Job.objects.filter(status='approved').update(status='accepted_quote')

class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0133_rename_job_status"),
    ]

    operations = [
        migrations.RunPython(convert_approved_to_accepted_quote, migrations.RunPython.noop),
    ]
