# Generated by Django 5.1.5 on 2025-04-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0134_alter_purchaseorder_order_date"),
    ]

    operations = [
    ]
