# Generated by Django 5.2 on 2025-05-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0133_bill_xero_tenant_id_client_xero_tenant_id_and_more"),
        ("workflow", "0134_auto_20250508_2012"),
    ]

    operations = []
