# Generated by Django 5.2 on 2025-05-08 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workflow", "0135_job_people_staff_icon_and_more")]

    operations = [
        # Staff models moved to accounts app - these changes are already there
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[],
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("quoting", "Quoting"),
                    ("accepted_quote", "Accepted Quote"),
                    ("awaiting_materials", "Awaiting Materials"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("special", "Special"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="quoting",
                max_length=30,
            ),
        ),
    ]
