# Generated by Django 5.2 on 2025-05-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0135_merge_20250508_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="status",
            field=models.CharField(
                choices=[
                    ("quoting", "Quoting"),
                    ("accepted_quote", "Accepted Quote"),
                    ("awaiting_materials", "Awaiting Materials"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("special", "Special"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="quoting",
                max_length=30,
            ),
        ),
    ]
