# Generated by Django 5.1.5 on 2025-04-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0135_job_people_staff_icon_and_more"),
    ]

    operations = [
    ]
