# Generated by Django 5.2 on 2025-05-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0131_aiprovider_companydefaults_anthropic_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="The job this stock item is assigned to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="workflow.job",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="source_purchase_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The PO line this stock originated from (if source='purchase_order')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_generated",
                to="workflow.purchaseorderline",
            ),
        ),
    ]
