# Generated by Django 5.1.5 on 2025-05-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0138_stock_job_stock_source_purchase_order_line"),
    ]

    operations = [
    ]
