# Generated by Django 5.1.5 on 2025-05-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0139_bill_xero_tenant_id_client_xero_tenant_id_and_more"),
    ]

    operations = [
    ]
