# Generated by Django 5.2 on 2025-05-10 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("workflow", "0139_bill_xero_tenant_id_client_xero_tenant_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="status",
            field=models.CharField(
                choices=[
                    ("quoting", "Quoting"),
                    ("accepted_quote", "Accepted Quote"),
                    ("awaiting_materials", "Awaiting Materials"),
                    ("in_progress", "In Progress"),
                    ("on_hold", "On Hold"),
                    ("special", "Special"),
                    ("completed", "Completed"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="quoting",
                max_length=30,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Nenhuma operação no banco
            state_operations=[
                migrations.RemoveField(
                    model_name="staff",
                    name="groups",
                ),
                migrations.RemoveField(
                    model_name="staff",
                    name="user_permissions",
                ),
                migrations.DeleteModel(
                    name="HistoricalStaff",
                ),
                migrations.DeleteModel(
                    name="Staff",
                ),
                migrations.CreateModel(
                    name="Staff",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("accounts.staff",),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="workflow.staff",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflow.staff",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="people",
            field=models.ManyToManyField(
                related_name="assigned_jobs", to="workflow.staff"
            ),
        ),
        migrations.AlterField(
            model_name="jobevent",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflow.staff",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="The Staff member who did the work.  Null for estimates/quotes.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_entries",
                to="workflow.staff",
            ),
        ),
    ]
