# Generated by Django 5.2 on 2025-05-13 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0001_initial"),
        ("workflow", "0140_remove_staff_groups_remove_staff_user_permissions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="timeentry",
                    name="job_pricing",
                ),
                migrations.RemoveField(
                    model_name="timeentry",
                    name="staff",
                ),
                migrations.DeleteModel(
                    name="TimeEntry",
                ),
                migrations.CreateModel(
                    name="TimeEntry",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("timesheet.timeentry",),
                ),
            ],
        ),
    ]