# Generated by Django 5.2 on 2025-05-15 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Mark migration as non-atomic

    dependencies = [
        ("job", "0001_initial"),
        ("timesheet", "0001_initial"),
        (
            "workflow",
            "0141_remove_timeentry_job_pricing_remove_timeentry_staff_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="historicaljob",
                    name="client",
                ),
                migrations.RemoveField(
                    model_name="historicaljob",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="historicaljob",
                    name="history_user",
                ),
                migrations.RemoveField(
                    model_name="historicaljob",
                    name="latest_estimate_pricing",
                ),
                migrations.RemoveField(
                    model_name="historicaljob",
                    name="latest_quote_pricing",
                ),
                migrations.RemoveField(
                    model_name="historicaljob",
                    name="latest_reality_pricing",
                ),
                migrations.RemoveField(
                    model_name="job",
                    name="archived_pricings",
                ),
                migrations.RemoveField(
                    model_name="job",
                    name="client",
                ),
                migrations.RemoveField(
                    model_name="job",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="job",
                    name="latest_estimate_pricing",
                ),
                migrations.RemoveField(
                    model_name="job",
                    name="latest_quote_pricing",
                ),
                migrations.RemoveField(
                    model_name="job",
                    name="latest_reality_pricing",
                ),
                migrations.RemoveField(
                    model_name="job",
                    name="people",
                ),
                migrations.RemoveField(
                    model_name="jobpricing",
                    name="job",
                ),
                migrations.RemoveField(
                    model_name="jobevent",
                    name="job",
                ),
                migrations.RemoveField(
                    model_name="jobfile",
                    name="job",
                ),
                migrations.RemoveField(
                    model_name="jobevent",
                    name="staff",
                ),
                migrations.AlterField(
                    model_name="adjustmententry",
                    name="job_pricing",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_entries",
                        to="job.jobpricing",
                    ),
                ),
                migrations.AlterField(
                    model_name="materialentry",
                    name="job_pricing",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_entries",
                        to="job.jobpricing",
                    ),
                ),
                migrations.RemoveField(
                    model_name="quotepricing",
                    name="jobpricing_ptr",
                ),
                migrations.DeleteModel(
                    name="Staff",
                ),
                migrations.DeleteModel(
                    name="HistoricalJob",
                ),
                migrations.DeleteModel(
                    name="Job",
                ),
                migrations.DeleteModel(
                    name="JobFile",
                ),
                migrations.DeleteModel(
                    name="JobEvent",
                ),
                migrations.DeleteModel(
                    name="JobPricing",
                ),
                migrations.DeleteModel(
                    name="QuotePricing",
                ),
                migrations.CreateModel(
                    name="Job",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("job.job",),
                ),
                migrations.CreateModel(
                    name="JobFile",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("job.jobfile",),
                ),
                migrations.CreateModel(
                    name="JobEvent",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("job.jobevent",),
                ),
                migrations.CreateModel(
                    name="JobPricing",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("job.jobpricing",),
                ),
            ],
            database_operations=[],  # No database operations will be performed
        ),
    ]
