# Generated by Django 5.1.5 on 2025-05-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0141_remove_timeentry_job_pricing_remove_timeentry_staff_and_more"),
    ]

    operations = [
    ]
