# Generated by Django 5.2 on 2025-05-18 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0142_remove_historicaljob_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="The job this stock item is assigned to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="job.job",
            ),
        ),
    ]
