# Generated by Django 5.2 on 2025-05-21 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_historicaljob_pricing_type_and_more"),
        ("timesheet", "0002_alter_timeentry_job_pricing_fk"),
        ("workflow", "0143_alter_stock_job"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="adjustmententry",
                    name="job_pricing",
                ),
                migrations.RemoveField(
                    model_name="materialentry",
                    name="job_pricing",
                ),
                migrations.RemoveField(
                    model_name="materialentry",
                    name="purchase_order_line",
                ),
                migrations.RemoveField(
                    model_name="materialentry",
                    name="source_stock",
                ),
                migrations.DeleteModel(
                    name="Job",
                ),
                migrations.DeleteModel(
                    name="JobEvent",
                ),
                migrations.DeleteModel(
                    name="JobFile",
                ),
                migrations.DeleteModel(
                    name="JobPricing",
                ),
                migrations.DeleteModel(
                    name="TimeEntry",
                ),
                migrations.AlterField(
                    model_name="invoice",
                    name="job",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="job.job",
                    ),
                ),
                migrations.AlterField(
                    model_name="purchaseorder",
                    name="job",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Primary job this PO is for",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="job.job",
                    ),
                ),
                migrations.AlterField(
                    model_name="purchaseorderline",
                    name="job",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="The job this purchase line is for",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_order_lines",
                        to="job.job",
                    ),
                ),
                migrations.AlterField(
                    model_name="quote",
                    name="job",
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote",
                        to="job.job",
                    ),
                ),
                migrations.DeleteModel(
                    name="AdjustmentEntry",
                ),
                migrations.DeleteModel(
                    name="MaterialEntry",
                ),
                migrations.CreateModel(
                    name="AdjustmentEntry",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("job.adjustmententry",),
                ),
                migrations.CreateModel(
                    name="MaterialEntry",
                    fields=[],
                    options={
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("job.materialentry",),
                ),
            ],
        )
    ]
