# Generated by Django 5.2 on 2025-05-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0145_fix_jobpricing_chain"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="AdjustmentEntry",
                ),
                migrations.DeleteModel(
                    name="MaterialEntry",
                ),
            ],
        ),
    ]
