# Generated by Django 5.2 on 2025-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0146_delete_adjustmententry_delete_materialentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="master_quote_template_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the master Google Sheets quote template",
                null=True,
            ),
        ),
    ]
