# Generated by Django 5.2 on 2025-05-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0147_companydefaults_po_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="primary_contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="primary_contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="secondary_contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="secondary_contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
