# Generated by Django 5.2 on 2025-05-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0150_client_all_phones"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydefaults",
            name="po_prefix",
            field=models.CharField(
                default="PO-",
                help_text="Prefix for purchase order numbers (e.g., PO-, JO-)",
                max_length=10,
            ),
        ),
    ]
