# Generated by Django 5.2 on 2025-06-02 06:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_alter_jobpart_options_and_more"),
        ("workflow", "0150_client_all_phones"),
    ]

    operations = [
        # UP TO HERE
        migrations.RemoveField(
            model_name="purchaseline",
            name="purchase",
        ),
        migrations.RemoveField(
            model_name="purchaseline",
            name="po_line",
        ),
        migrations.RenameField(
            model_name="bill",
            old_name="total",
            new_name="total_excl_tax",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="total",
            new_name="total_excl_tax",
        ),
        migrations.AddField(
            model_name="bill",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bill",
            name="total_incl_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bill",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="master_quote_template_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the master Google Sheets quote template",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="companydefaults",
            name="starting_job_number",
            field=models.IntegerField(
                default=1,
                help_text="Helper field to set the starting job number based on the latest paper job",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="job.job",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="online_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_incl_tax",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary job this PO is for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="job.job",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="alloy",
            field=models.CharField(
                blank=True,
                help_text="Alloy specification (e.g., 304, 6061)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="The job this purchase line is for",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_lines",
                to="job.job",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Where this item will be stored",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminum", "Aluminum"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                default="unspecified",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="specifics",
            field=models.CharField(
                blank=True,
                help_text="Specific details (e.g., m8 countersunk socket screw)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="xeroaccount",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="xerojournal",
            name="xero_last_synced",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="xerojournal",
            name="xero_tenant_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="po_lines",
                to="workflow.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date the stock item was created",
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="metal_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stainless_steel", "Stainless Steel"),
                    ("mild_steel", "Mild Steel"),
                    ("aluminum", "Aluminum"),
                    ("brass", "Brass"),
                    ("copper", "Copper"),
                    ("titanium", "Titanium"),
                    ("zinc", "Zinc"),
                    ("galvanized", "Galvanized"),
                    ("unspecified", "Unspecified"),
                    ("other", "Other"),
                ],
                default="unspecified",
                help_text="Type of metal",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="xeroaccount",
            name="account_name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="xerotoken",
            name="scope",
            field=models.TextField(
                default="offline_access openid profile email accounting.contacts accounting.transactions accounting.reports.read accounting.settings accounting.journals.read"
            ),
        ),
        migrations.AlterModelTable(
            name="bill",
            table=None,
        ),
        migrations.AlterModelTable(
            name="client",
            table=None,
        ),
        migrations.AlterModelTable(
            name="companydefaults",
            table=None,
        ),
        migrations.AlterModelTable(
            name="invoice",
            table=None,
        ),
        migrations.AlterModelTable(
            name="stock",
            table=None,
        ),
        migrations.AlterModelTable(
            name="xeroaccount",
            table=None,
        ),
        migrations.AlterModelTable(
            name="xerotoken",
            table=None,
        ),
        migrations.CreateModel(
            name="BillLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_line_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_incl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workflow.xeroaccount",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="workflow.bill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill Line Item",
                "verbose_name_plural": "Bill Line Items",
            },
        ),
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("number", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("AUTHORISED", "Authorised"),
                            ("DELETED", "Deleted"),
                            ("VOIDED", "Voided"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "total_excl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("xero_last_modified", models.DateTimeField()),
                (
                    "xero_last_synced",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("django_created_at", models.DateTimeField(auto_now_add=True)),
                ("django_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Note",
                "verbose_name_plural": "Credit Notes",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CreditNoteLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_line_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_incl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workflow.xeroaccount",
                    ),
                ),
                (
                    "credit_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="workflow.creditnote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Note Line Item",
                "verbose_name_plural": "Credit Note Line Items",
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_line_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_excl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "line_amount_incl_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workflow.xeroaccount",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="workflow.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Line Item",
                "verbose_name_plural": "Invoice Line Items",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("xero_id", models.UUIDField(unique=True)),
                (
                    "xero_tenant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENT", "Sent"),
                            ("DECLINED", "Declined"),
                            ("ACCEPTED", "Accepted"),
                            ("INVOICED", "Invoiced"),
                            ("DELETED", "Deleted"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "total_excl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_incl_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("xero_last_modified", models.DateTimeField(blank=True, null=True)),
                (
                    "xero_last_synced",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("online_url", models.URLField(blank=True, null=True)),
                ("raw_json", models.JSONField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.client",
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote",
                        to="job.job",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Purchase",
        ),
        migrations.DeleteModel(
            name="PurchaseLine",
        ),
    ]
