# Generated by Django 5.2 on 2025-06-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0152_remove_companydefaults_anthropic_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="raw_json",
            field=models.JSONField(
                blank=True, help_text="Raw JSON data from Xero for this item", null=True
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="xero_id",
            field=models.CharField(
                blank=True,
                help_text="Unique ID from Xero for this item",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="xero_last_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Last modified date from Xero for this item",
                null=True,
            ),
        ),
    ]
