# Generated by Django 5.2 on 2025-06-04 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0153_delete_client_client"),
        ("workflow", "0153_stock_raw_json_stock_xero_id_and_more"),
    ]

    operations = []
