# Generated by Django 5.2 on 2025-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0154_merge_20250605_0623"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="item_code",
            field=models.CharField(
                default="legacy", help_text="Xero Item Code", max_length=255
            ),
            preserve_default=False,
        ),
    ]
