# Generated by Django 5.2 on 2025-06-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "job",
            "0011_rename_revenue_adjustment_adjustmententry_price_adjustment_and_more",
        ),
        ("workflow", "0155_stock_item_code"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.UniqueConstraint(
                fields=("xero_id",), name="unique_xero_id_stock"
            ),
        ),
    ]
