# Generated by Django 5.2 on 2025-05-15 22:56

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False  # Mark migration as non-atomic

    initial = True

    dependencies = [
        (
            "workflow",
            "0141_remove_timeentry_job_pricing_remove_timeentry_staff_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="JobPricing",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "pricing_stage",
                            models.CharField(
                                choices=[
                                    ("estimate", "Estimate"),
                                    ("quote", "Quote"),
                                    ("reality", "Reality"),
                                ],
                                default="estimate",
                                help_text="Stage of the job pricing (estimate, quote, or reality).",
                                max_length=20,
                            ),
                        ),
                        (
                            "revision_number",
                            models.PositiveIntegerField(
                                default=1,
                                help_text="Tracks the revision number for friendlier quotes",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("is_historical", models.BooleanField(default=False)),
                    ],
                    options={
                        "db_table": "workflow_jobpricing",
                        "ordering": ["-created_at", "pricing_stage"],
                    },
                ),
                migrations.CreateModel(
                    name="Job",
                    fields=[
                        ("name", models.CharField(max_length=100)),
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "order_number",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "contact_person",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "contact_phone",
                            models.CharField(blank=True, max_length=15, null=True),
                        ),
                        ("job_number", models.IntegerField(unique=True)),
                        (
                            "material_gauge_quantity",
                            models.TextField(
                                blank=True,
                                help_text="DEPRECATED - Use notes field instead. Content will be automatically migrated.",
                                null=True,
                            ),
                        ),
                        (
                            "description",
                            models.TextField(
                                blank=True,
                                help_text="This becomes the first line item on the invoice",
                                null=True,
                            ),
                        ),
                        ("quote_acceptance_date", models.DateTimeField(blank=True, null=True)),
                        ("delivery_date", models.DateField(blank=True, null=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("quoting", "Quoting"),
                                    ("accepted_quote", "Accepted Quote"),
                                    ("awaiting_materials", "Awaiting Materials"),
                                    ("in_progress", "In Progress"),
                                    ("on_hold", "On Hold"),
                                    ("special", "Special"),
                                    ("completed", "Completed"),
                                    ("rejected", "Rejected"),
                                    ("archived", "Archived"),
                                ],
                                default="quoting",
                                max_length=30,
                            ),
                        ),
                        ("job_is_valid", models.BooleanField(default=False)),
                        ("collected", models.BooleanField(default=False)),
                        ("paid", models.BooleanField(default=False)),
                        (
                            "charge_out_rate",
                            models.DecimalField(decimal_places=2, max_digits=10),
                        ),
                        (
                            "pricing_type",
                            models.CharField(
                                choices=[
                                    ("fixed_price", "Fixed Price"),
                                    ("time_materials", "Time & Materials"),
                                ],
                                default="time_materials",
                                help_text="Type of pricing for the job (fixed price or time and materials).",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("complex_job", models.BooleanField(default=False)),
                        (
                            "notes",
                            models.TextField(
                                blank=True,
                                help_text="Internal notes about the job. Not shown on the invoice.",
                                null=True,
                            ),
                        ),
                        (
                            "client",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="jobs",
                                to="workflow.client",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "people",
                            models.ManyToManyField(
                                related_name="assigned_jobs", to=settings.AUTH_USER_MODEL
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Job",
                        "verbose_name_plural": "Jobs",
                        "db_table": "workflow_job",
                        "ordering": ["job_number"],
                    },
                ),
                migrations.CreateModel(
                    name="JobEvent",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                        (
                            "event_type",
                            models.CharField(default="automatic_event", max_length=100),
                        ),
                        ("description", models.TextField()),
                        (
                            "job",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="events",
                                to="job.job",
                            ),
                        ),
                        (
                            "staff",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "db_table": "workflow_jobevent",
                        "ordering": ["-timestamp"],
                    },
                ),
                migrations.CreateModel(
                    name="JobFile",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("filename", models.CharField(max_length=255)),
                        ("file_path", models.CharField(max_length=500)),
                        ("mime_type", models.CharField(blank=True, max_length=100)),
                        ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[("active", "Active"), ("deleted", "Deleted")],
                                default="active",
                                max_length=20,
                            ),
                        ),
                        ("print_on_jobsheet", models.BooleanField(default=True)),
                        (
                            "job",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="files",
                                to="job.job",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "workflow_jobfile",
                        "ordering": ["-uploaded_at"],
                    },
                ),
                migrations.CreateModel(
                    name="QuotePricing",
                    fields=[
                        (
                            "jobpricing_ptr",
                            models.OneToOneField(
                                auto_created=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                parent_link=True,
                                primary_key=True,
                                serialize=False,
                                to="job.jobpricing",
                            ),
                        ),
                        ("quote_is_finished", models.BooleanField(default=False)),
                        ("date_quote_submitted", models.DateField(blank=True, null=True)),
                        ("quote_number", models.IntegerField(unique=True)),
                    ],
                    options={
                        "db_table": "workflow_quotepricing",
                    },
                    bases=("job.jobpricing",),
                ),
                migrations.AddField(
                    model_name="jobpricing",
                    name="job",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricings",
                        to="job.job",
                    ),
                ),
                migrations.AddField(
                    model_name="job",
                    name="archived_pricings",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="archived_pricings_for_job",
                        to="job.jobpricing",
                    ),
                ),
                migrations.AddField(
                    model_name="job",
                    name="latest_estimate_pricing",
                    field=models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_estimate_for_job",
                        to="job.jobpricing",
                    ),
                ),
                migrations.AddField(
                    model_name="job",
                    name="latest_quote_pricing",
                    field=models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_quote_for_job",
                        to="job.jobpricing",
                    ),
                ),
                migrations.AddField(
                    model_name="job",
                    name="latest_reality_pricing",
                    field=models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latest_reality_for_job",
                        to="job.jobpricing",
                    ),
                ),
                migrations.CreateModel(
                    name="HistoricalJob",
                    fields=[
                        ("name", models.CharField(max_length=100)),
                        (
                            "id",
                            models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                        ),
                        (
                            "order_number",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "contact_person",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "contact_phone",
                            models.CharField(blank=True, max_length=15, null=True),
                        ),
                        ("job_number", models.IntegerField(db_index=True)),
                        (
                            "material_gauge_quantity",
                            models.TextField(
                                blank=True,
                                help_text="DEPRECATED - Use notes field instead. Content will be automatically migrated.",
                                null=True,
                            ),
                        ),
                        (
                            "description",
                            models.TextField(
                                blank=True,
                                help_text="This becomes the first line item on the invoice",
                                null=True,
                            ),
                        ),
                        ("quote_acceptance_date", models.DateTimeField(blank=True, null=True)),
                        ("delivery_date", models.DateField(blank=True, null=True)),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("quoting", "Quoting"),
                                    ("accepted_quote", "Accepted Quote"),
                                    ("awaiting_materials", "Awaiting Materials"),
                                    ("in_progress", "In Progress"),
                                    ("on_hold", "On Hold"),
                                    ("special", "Special"),
                                    ("completed", "Completed"),
                                    ("rejected", "Rejected"),
                                    ("archived", "Archived"),
                                ],
                                default="quoting",
                                max_length=30,
                            ),
                        ),
                        ("job_is_valid", models.BooleanField(default=False)),
                        ("collected", models.BooleanField(default=False)),
                        ("paid", models.BooleanField(default=False)),
                        (
                            "charge_out_rate",
                            models.DecimalField(decimal_places=2, max_digits=10),
                        ),
                        (
                            "pricing_type",
                            models.CharField(
                                choices=[
                                    ("fixed_price", "Fixed Price"),
                                    ("time_materials", "Time & Materials"),
                                ],
                                default="time_materials",
                                help_text="Type of pricing for the job (fixed price or time and materials).",
                                max_length=20,
                            ),
                        ),
                        ("created_at", models.DateTimeField(blank=True, editable=False)),
                        ("updated_at", models.DateTimeField(blank=True, editable=False)),
                        ("complex_job", models.BooleanField(default=False)),
                        (
                            "notes",
                            models.TextField(
                                blank=True,
                                help_text="Internal notes about the job. Not shown on the invoice.",
                                null=True,
                            ),
                        ),
                        ("history_id", models.AutoField(primary_key=True, serialize=False)),
                        ("history_date", models.DateTimeField(db_index=True)),
                        ("history_change_reason", models.CharField(max_length=100, null=True)),
                        (
                            "history_type",
                            models.CharField(
                                choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                                max_length=1,
                            ),
                        ),
                        (
                            "client",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to="workflow.client",
                            ),
                        ),
                        (
                            "created_by",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "history_user",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="+",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "latest_estimate_pricing",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to="job.jobpricing",
                            ),
                        ),
                        (
                            "latest_quote_pricing",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to="job.jobpricing",
                            ),
                        ),
                        (
                            "latest_reality_pricing",
                            models.ForeignKey(
                                blank=True,
                                db_constraint=False,
                                null=True,
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="+",
                                to="job.jobpricing",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "historical Job",
                        "verbose_name_plural": "historical Jobs",
                        "ordering": ("-history_date", "-history_id"),
                        "get_latest_by": ("history_date", "history_id"),
                        "db_table": "workflow_historicaljob",
                    },
                    bases=(simple_history.models.HistoricalChanges, models.Model),
                ),
            ],
            database_operations=[],  # No database operations will be performed
        ),
    ]
