# Generated by Django 5.2 on 2025-05-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_historicaljob_pricing_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="linked_quote",
            field=models.URLField(
                blank=True, help_text="URL to a linked Google Sheets quote", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="linked_quote",
            field=models.URLField(
                blank=True, help_text="URL to a linked Google Sheets quote", null=True
            ),
        ),
    ]
