# Generated by Django 5.2 on 2025-05-28 21:16

from django.db import migrations


def create_default_parts(apps, schema_editor):
    """
    Create a default 'Main Work' part for each existing JobPricing and
    assign all existing entries to this part.
    """
    JobPricing = apps.get_model('job', 'JobPricing')
    Part = apps.get_model('job', 'Part')
    MaterialEntry = apps.get_model('job', 'MaterialEntry')
    AdjustmentEntry = apps.get_model('job', 'AdjustmentEntry')
    TimeEntry = apps.get_model('timesheet', 'TimeEntry')
    
    # Create a default part for each JobPricing
    for job_pricing in JobPricing.objects.all():
        # Create the default part
        default_part = Part.objects.create(
            job_pricing=job_pricing,
            name="Main Work",
            description="Default part created during migration"
        )
        
        # Assign all material entries to this part
        MaterialEntry.objects.filter(job_pricing=job_pricing, part__isnull=True).update(part=default_part)
        
        # Assign all adjustment entries to this part
        AdjustmentEntry.objects.filter(job_pricing=job_pricing, part__isnull=True).update(part=default_part)
        
        # Assign all time entries to this part
        TimeEntry.objects.filter(job_pricing=job_pricing, part__isnull=True).update(part=default_part)


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by setting all part references to null.
    """
    MaterialEntry = apps.get_model('job', 'MaterialEntry')
    AdjustmentEntry = apps.get_model('job', 'AdjustmentEntry')
    TimeEntry = apps.get_model('timesheet', 'TimeEntry')
    Part = apps.get_model('job', 'Part')
    
    # Set all part references to null
    MaterialEntry.objects.all().update(part=None)
    AdjustmentEntry.objects.all().update(part=None)
    TimeEntry.objects.all().update(part=None)
    
    # Delete all parts
    Part.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_part_adjustmententry_part_materialentry_part"),
        ("timesheet", "0003_timeentry_part"),  # Add dependency on timesheet migration
    ]

    operations = [
        migrations.RunPython(create_default_parts, reverse_migration),
    ]
