# Generated by Django 5.1.5 on 2025-06-02 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_historicaljob_contact_phone_and_more'),
        ('workflow', '0146_delete_adjustmententry_delete_materialentry'),
    ]

    operations = [
    ]