# Generated by Django 5.2 on 2025-05-28 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_historicaljob_linked_quote_job_linked_quote"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="job.jobpricing",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_part",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="adjustmententry",
            name="part",
            field=models.ForeignKey(
                blank=True,
                help_text="The part this adjustment entry belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustment_entries",
                to="job.part",
            ),
        ),
        migrations.AddField(
            model_name="materialentry",
            name="part",
            field=models.ForeignKey(
                blank=True,
                help_text="The part this material entry belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_entries",
                to="job.part",
            ),
        ),
    ]
