# Generated by Django 5.2 on 2025-06-02 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_add_material_adjustment_jobpart_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobpart",
            options={"ordering": ["created_at"]},
        ),
        migrations.RenameField(
            model_name="adjustmententry",
            old_name="revenue_adjustment",
            new_name="price_adjustment",
        ),
        migrations.RemoveField(
            model_name="jobpart",
            name="job",
        ),
        migrations.AddField(
            model_name="jobpart",
            name="job_pricing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="job.jobpricing",
            ),
        ),
        migrations.AddField(
            model_name="jobpricing",
            name="default_part",
            field=models.OneToOneField(
                blank=True,
                help_text="The default 'Main Work' part associated with this JobPricing instance. This part typically holds general time and material entries for the given pricing type.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_job_pricing",
                to="job.jobpart",
            ),
        ),
        migrations.AlterField(
            model_name="adjustmententry",
            name="comments",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="adjustmententry",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="created_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="updated_at",
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name="jobpart",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name="jobpart",
            table="workflow_part",
        ),
    ]
