# Generated by Django 5.2 on 2025-06-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_add_material_adjustment_jobpart_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name="jobpart", name="job"),
                migrations.AddField(
                    model_name="jobpart",
                    name="job_pricing",
                    field=models.ForeignKey(
                        null=True,
                        blank=True,
                        on_delete=models.CASCADE,
                        to="job.jobpricing",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
