# Generated by Django 5.2 on 2025-05-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_create_default_parts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaljob",
            old_name="pricing_type",
            new_name="pricing_methodology",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="pricing_type",
            new_name="pricing_methodology",
        ),
    ]
