# Generated by Django 5.2 on 2025-05-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_create_default_parts"),
    ]

    operations = [
        # No operations needed - the database already has the correct 'pricing_methodology' field
        # Migration 0002 incorrectly created a phantom 'pricing_type' field in Django's state
        # but the actual database column was always named 'pricing_methodology' from 0001_initial
    ]
