# Generated by Django 5.2 on 2025-05-29 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_rename_pricing_type_historicaljob_pricing_methodology_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="pricing_methodology",
            field=models.CharField(
                choices=[
                    ("time_materials", "Time and Materials"),
                    ("fixed_price", "Fixed Price"),
                ],
                default="time_materials",
                help_text="Type of pricing for the job (fixed price or time and materials).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="pricing_methodology",
            field=models.CharField(
                choices=[
                    ("time_materials", "Time and Materials"),
                    ("fixed_price", "Fixed Price"),
                ],
                default="time_materials",
                help_text="Type of pricing for the job (fixed price or time and materials).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobpricing",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("estimate", "Estimate"),
                    ("quote", "Quote"),
                    ("reality", "Reality"),
                ],
                default="estimate",
                help_text="Stage of the job pricing (estimate, quote, or reality).",
                max_length=20,
            ),
        ),
    ]
