# Generated by Django 5.2 on 2025-05-29 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0009_alter_historicaljob_pricing_methodology_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpricing",
            name="default_part",
            field=models.OneToOneField(
                blank=True,
                help_text="The default 'Main Work' part for this JobPricing",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="default_for_job_pricing",
                to="job.part",
            ),
        ),
    ]
