# Generated by Django 5.2 on 2025-06-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_populate_priority_for_existing_jobs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adjustmententry",
            old_name="revenue_adjustment",
            new_name="price_adjustment",
        ),
    ]
