# Generated by Django 5.2 on 2025-05-31 10:24

from django.db import migrations, models
import django.db.models.deletion


def validate_parts_exist(apps, schema_editor):
    """Validate that all MaterialEntry and AdjustmentEntry records have parts assigned"""
    MaterialEntry = apps.get_model("job", "MaterialEntry")
    AdjustmentEntry = apps.get_model("job", "AdjustmentEntry")
    
    # Check MaterialEntry records
    material_entries_without_parts = MaterialEntry.objects.filter(part__isnull=True).count()
    if material_entries_without_parts > 0:
        raise Exception(
            f"Cannot proceed: {material_entries_without_parts} MaterialEntry records "
            "do not have parts assigned. Please run the data migration first."
        )
    
    # Check AdjustmentEntry records
    adjustment_entries_without_parts = AdjustmentEntry.objects.filter(part__isnull=True).count()
    if adjustment_entries_without_parts > 0:
        raise Exception(
            f"Cannot proceed: {adjustment_entries_without_parts} AdjustmentEntry records "
            "do not have parts assigned. Please run the data migration first."
        )
    
    print(f"✓ Validation passed: All MaterialEntry and AdjustmentEntry records have parts assigned")


def reverse_validation(apps, schema_editor):
    """No validation needed for reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0010_jobpricing_default_part"),
    ]

    operations = [
        migrations.RunPython(validate_parts_exist, reverse_validation),
        migrations.RemoveField(
            model_name="materialentry",
            name="job_pricing",
        ),
        migrations.RemoveField(
            model_name="adjustmententry",
            name="job_pricing",
        ),
        migrations.AlterField(
            model_name="materialentry",
            name="part",
            field=models.ForeignKey(
                help_text="The part this material entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="material_entries",
                to="job.part",
            ),
        ),
        migrations.AlterField(
            model_name="adjustmententry",
            name="part",
            field=models.ForeignKey(
                help_text="The part this adjustment entry belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjustment_entries",
                to="job.part",
            ),
        ),
    ]